var nm1 = ["KwadwÃ³ (Monday)","KwabenÃ¡ (Tuesday)","KwakÃº (Wednesday)","Yaw (Thursday)","KofÃ­ (Friday)","KwÃ¡mÃ¨ (Saturday)","KwÇmÃ¨ (Saturday)","KwasÃ­ (Sunday)","KodjÃ³ (Monday)","Kojo (Monday)","Jojo (Monday)","Cudjoe (Monday)","KomlÃ¡ (Tuesday)","KomlÃ£ (Tuesday)","Komlan (Tuesday)","Kabenla Kobby (Tuesday)","Ebo (Tuesday)","Kobi Kobina (Tuesday)","Koku (Wednesday)","Kokou (Wednesday)","Kweku (Wednesday)","Kaku (Wednesday)","Kuuku (Wednesday)","Yao (Thursday)","Yaba (Thursday)","Yawo (Thursday)","Ekow (Thursday)","Kow (Thursday)","Kwaw (Thursday)","Koffi (Friday)","Fiifi (Friday)","Yoofi (Friday)","Ato (Saturday)","Kwami (Saturday)","Kuwame (Saturday)","Kwamena (Saturday)","Kwamina (Saturday)","Komi (Saturday)","Kwesi (Sunday)","Siisi (Sunday)","Akwasi (Sunday)","Kosi (Sunday)","AtÃ¡ (Twin)","AtÃ¡ PÃ¡nin (Younger Twin)","AtÃ¡ KÃºmaa (Elder Twin)","TÃ¡wia (Born after twins)","Gaddo (Born after 'TÃ¡wia')","PÃ­Ã¨sÃ­e (First Born)","MÇnu (Second Born)","MeÅsÃ£Ì (Third Born)","Anan (Fourth Born)","AnanÃ© (Fourth Born)","NÃºm (Fifth Born)","AnÃºm (Fifth Born)","NsÄ©Ã£Ì (Sixth Born)","AsÃ³n (Seventh Born)","BÃ³twe (Eight Born)","Ãkron (Ninth Born)","NkrÃ³ma (Ninth Born)","BadÃº (Tenth Born)","DÃºkÅ© (Eleventh Born)","DÃºnu (Twelfth Born)","Kaakyire (Last Born)","Mensah (Third Born)","Mansah (Third Born)","Annan (Fourth Born)","Essien (Sixth Born)","Esson (Seventh Born)","Ansong (Seventh Born)","Awotwe (Eight Born)","Awotwie (Eight Born)","Akun (Ninth Born)","Ackon (Ninth Born)","Nkrumah (Ninth Born)","Bedu (Tenth Born)","Berko (First Born)","Arko (First Born)","AfÃºom (On the field)","ÆkwÃ¡n (On the road)","Beká¹e (In war)","AfirÃ­yie (Happy circumstances)","Adofo (Loving circumstances)","Agyenim (Great one)","NyamÃ©kyÎµ (After long childlessness)","NyamÃ©ama (Premature)","Kumi (Forcefully)","AntÃ³ (After death of father)","ObÃ­mÌpÎ­ (Father refuses)","YÎµmpÎ­w (Father refuses)"];
var nm2 = ["Adwoa (Monday)","Abenaa (Tuesday)","AbÃ©naa (Tuesday)","Akua (Wednesday)","AkÃºÃ¡ (Wednesday)","Akuba (Wednesday)","Yaa (Thursday)","Afua (Friday)","ÃmÌma (Saturday)","ÃmmÃ¡ (Saturday)","Akosua (Sunday)","Adjua (Monday)","Ajwoba (Monday)","Adjoa (Monday)","Adjowa (Monday)","AblÃ¡ (Tuesday)","AblÃ£ (Tuesday)","Abena (Tuesday)","Araba (Tuesday)","Abrema (Tuesday)","AkÃº (Wednesday)","Ekua (Wednesday)","Ayawa (Thursday)","Baaba (Thursday)","Yaaba (Thursday)","Aba (Thursday)","AfÃ­ (Friday)","Afua (Friday)","Efia (Friday)","Efua (Friday)","Ame (Saturday)","Ama (Saturday)","Ami (Saturday)","Amba (Saturday)","Ameyo (Saturday)","Akosi (Sunday)","Akosiwa (Sunday)","AsÃ­ (Sunday)","Esi (Sunday)","Kwasiba (Sunday)","AtaÃ¡ (Twin)","AtaÃ¡ PÃ¡nin (Younger Twin)","AtaÃ¡ KÃºmaa (Elder Twin)","TÃ¡wia (Born after twins)","NyankÃ³mÃ gÃ³ (Born after 'TÃ¡wia')","Mensah (Third Born)","Mansah (Third Born)","Annan (Fourth Born)","Essien (Sixth Born)","Esson (Seventh Born)","Ansong (Seventh Born)","Awotwe (Eight Born)","Awotwie (Eight Born)","Akun (Ninth Born)","Ackon (Ninth Born)","Nkrumah (Ninth Born)","Bedu (Tenth Born)","Dede (First Born)","Dedei (First Born)","Abaka (First Born)","Kande (First Born)","PÃ­Ã¨sÃ­e (First Born)","MÃ¡anu (Second Born)","MÃ¡nsÃ£ (Third Born)","Anan (Fourth Born)","AnanÃ© (Fourth Born)","NÃºm (Fifth Born)","AnÃºm (Fifth Born)","NsÄ©Ã£Ì (Sixth Born)","Nsá¹waa (Seventh Born)","BÃ³twe (Eight Born)","NkrÃ³ma (Ninth Born)","BadÃºwaa (Tenth Born)","DÃºkÅ© (Eleventh Born)","DÃºnu (Twelfth Born)","Kaakyire (Last Born)","BedÃ­Ã ká¹ (In war)","AfÃºom (On the field)","ÆkwÃ¡n (On the road)","AfirÃ­yie (Happy circumstances)","Adofo (Loving circumstances)","Agyenim (Great one)","NyamÃ©kyÎµ (After long childlessness)","NyamÃ©ama (Premature)","Kumi (Forcefully)","AntÃ³ (After death of father)","ObÃ­mÌpÎ­ (Father refuses)","YÎµmpÎ­w (Father refuses)"];
var nm3 = ["Abeberese","Abeyie","Aboagye","Aboah","Aborah","Aborampah","Abrafi","Abrefa","Achamfour","Acheampong","Acquah","Adade","Addai","Addo","Adiyiah","Adomah","Adomako","Adusei","Adwubi","Afful","Afirifa","Afoakwah","Afrakoma","Afrakomah","Afram","Afrane","Afreh","Afrifa","Afriyie","Agyapong","Agyare","Agyei","Agyeman","Agyemang","Ahinful","Akaminko","Akenten","Akenteng","Akomeah","Akomfrah","Akosah","Akoto","Akrofi","Akuamoah","Akuffo","Akyaw","Amakye","Amamfo","Amankona","Amankonah","Amankwah","Ameyaw","Amissah","Amoabeng","Amoah","Amoako","Amoateng","Amofah","Ampadu","Ampem","Ampofo","Amponsah","Amponsem","Andoh","Ankobiah","Ankomah","Ankrah","Annan","Anokye","Ansah","Apau","Apori Antwi","Appiah","Arkorful","Asamoah","Asante","Asantewaa","Asare","Asenso","Ashia","Asiamah","Asiedu","Asomadu","Asomaning","Assifuah","Asubonteng","Awuah","Ayeh","Ayensu","Ayew","Baafi","Baah","Baako","Baffoe","Bafuor","Baidoo","Banahene","Barwuah","Bediako","Bekoe","Bemah","Boadi","Boadu","Boahen","Boakye","Boamah","Boampong","Boasiako","Boatei","Boateng","Bonah","Bonsra","Bonsrah","Bonsu","Brempong","Busia","Busiah","Cofie","Crentsil","Cuffee","Daako","Dankwah","Danquah","Danso","Dapaa","Dapaah","Darko","Diawuo","Djan","Djansi","Domfe","Donkor","Dorkenoo","Duah","Dufie","Duodu","Dwamena","Dwamenah","Dwomoh","Ekuoba","Enninful","Essien","Farkyi","Firikyi","Fofie","Fokuo","Fordjour","Forobuor","Fredua","Freduah","Fremah","Frempon","Frempong","Frimpong","Gyaama","Gyakari","Gyamah","Gyambibi","Gyamera","Gyamerah","Gyamfi","Gyan","Gyasi","Gyeabuor","Gyimah","Inkoom","Karikari","Katakyie","Kenu","Koduah","Kofi","Kokote","Konadu","Koranten","Koranteng","Korsah","Kouassi","Kuffour","Kufuor","Kumankama","Kusi","Kusiwaa","Kwaata","Kwakye","Kwarteng","Kwateng","Kwayie","Kyei","Kyekyeku","Kyem","Kyerematen","Kyeremateng","Kyereme","Kyerewa","Kyerewaa","Manso","Mensah","Mintah","Misa","Mmorosa","Mpong","Munuo","Narh","Nduom","Nimo","Nimoh","Nkansa","Nkansah","Nkrumah","Nsiah","Nsonwaa","Nsonwah","Nsor","Ntiamoa","Ntiamoah","Ntim","Ntow","Nuamah","Nyamekye","Nyankomago","Nyantah","Nyantakyi","Nyarko","Obeng","Obuor","Oduro","Ofori","Ofosu","Ogyampah","Ohemeng","Ohene","Okese","Okoromansah","Okyere","Omenaa","Omenah","Opambuor","Opare","Opoku","Oppong","Opuni","Osafo","Osam","Osei","Oteng","Otuo","Owoahene","Owusu","Oyiakwan","Paintsil","Pappoe","Peprah","Pinaman","Poku","Prempeh","Quainoo","Quansah","Safo","Sakyi","Sarfo","Sarkodie","Sarpei","Sarpon","Sarpong","Sasraku","Siabuor","Siaw","Sika","Sikafuo","Sintim","Siriboe","Soadwa","Soadwah","Sowah","Tagoe","Takyi","Tandoh","Tawiah","Tuffour","Twasam","Tweneboa","Tweneboah","Twerefuo","Twum","Twumasi","Vorsah","Wiafe","Wiredu","Yamoah","Yankah","Yartei","Yeboah","Yiadom"];
var br = "";

function nameGen(type){
	$('#placeholder').css('textTransform', 'capitalize');
	var tp = type;
	var element = document.createElement("div");
	element.setAttribute("id", "result");
	
	for(i = 0; i < 10; i++){
		rnd2 = Math.floor(Math.random() * nm3.length);
		if(tp === 1){
			rnd = Math.floor(Math.random() * nm2.length);
			names = nm2[rnd] + " " + nm3[rnd2];
		}else{
			rnd = Math.floor(Math.random() * nm1.length);
			names = nm1[rnd] + " " + nm3[rnd2];
		}
		br = document.createElement('br');	
		element.appendChild(document.createTextNode(names));
		element.appendChild(br);
	}
	if(document.getElementById("result")){
		document.getElementById("placeholder").removeChild(document.getElementById("result"));
	}		
	document.getElementById("placeholder").appendChild(element);
}