var nm1 = ["","","","","Abandoned","Aberrant","Acid","Acrid","Adamant","Agile","Anchored","Ancient","Anguished","Arctic","Beautiful","Berserk","Bitter","Black","Bleak","Blind","Blue","Bold","Brave","Bright","Brilliant","Broken","Bronze","Burning","Careless","Ceaseless","Colossal","Corrupt","Corrupted","Craven","Crooked","Cruel","Curious","Dark","Defiant","Demonic","Diligent","Divergent","Enchanted","Enraged","Eternal","Ethereal","Exalted","Faint","False","Fearless","Flawed","Flawless","Forsaken","Fragrant","Frozen","Giant","Golden","Graceful","Grand","Grim","Hallowed","Heavenly","Hidden","Hollow","Honored","Hungry","Infernal","Invincible","Jade","Jubilant","Light","Little","Livid","Lone","Lost","Lucky","Mad","Majestic","Marked","Masked","Merciful","Merciless","Monstrous","Mysterious","Noxious","Powerful","Primal","Primeval","Putrid","Quiet","Rabid","Radiant","Reckless","Regal","Royal","Ruthless","Sanguine","Sapphire","Serene","Shadowy","Silent","Silver","Skeletal","Spiritual","Swift","Tranquil","Twin","Vagabond","Vengeful","Venomous","Vibrant","Vicious","Vigilant","Violent","Volatile","Wicked","Wrathful","Wretched"];
var nm2 = ["Anger","Aqua","Arch","Ash","Autumn","Beast","Blood","Chain","Chaos","Chrono","Cloud","Crime","Crimson","Crown","Dark","Dead","Death","Demon","Devil","Dimension","Dragon","Dream","Ember","Fire","Flame","Fog","Ghost","Glass","Gold","Hell","Ice","Iron","Jade","Light","Metal","Mind","Moon","Night","Phantom","Phase","Poison","Shadow","Silver","Smoke","Space","Spell","Spirit","Spring","Star","Storm","Summer","Sun","Thunder","Venom","Winter","World"];
var nm3 = ["Anaconda","Angel","Anger","Animal","Ape","Arachnid","Arm","Arm of the Law","Army","Aspect","Autumn Leaf","Avalanche","Baboon","Badger","Bane","Basilisk","Bat","Beam","Bear","Beast","Beetle","Behemoth","Bell","Belt","Bird","Birth","Blade","Blizzard","Blood","Blossoms","Boa","Boar","Bolt","Bone","Book","Boulder","Branch","Breath","Bubble","Bull","Burst","Candle","Canine","Cannon","Carriage","Cat","Chain","Champion","Charge","Chariot","Circle","Claw","Clock","Cloud","Clover","Cobra","Cocoon","Coil","Collar","Comet","Command","Contract","Cord","Crab","Crane","Creature","Crescent","Cross","Crow","Crown","Curtain","Dance","Death","Demon","Design","Devil","Dimension","Disk","Dog","Doll","Dragon","Drum","Duo","Dust","Dust Storm","Eagle","Earth","Earthquake","Elephant","Eye","Eyes","Face","Falcon","Familiar","Fang","Fangs","Feast","Feather","Fire","Fist","Flame","Flesh","Flock","Flock of Crows","Flower","Force","Fork","Fox","Fruit","Gate","Gator","Ghost","Giant","Gift","Glove","God","Golem","Gorilla","Grace","Grief","Grip","Guard","Guardian","Guest","Halo","Hammer","Hand","Handle","Hare","Hawk","Heart","Hell","Hook","Hornet","Horror","Hound","Hunter","Hurricane","Ice","Image","Inferno","Insect","Jackal","Jaguar","Jaw","Jewel","Judge","Judgment","Katana","King","Knife","Leaf","Leech","Leviathan","Light","Lion","Locket","Locust","Mandrill","Mantis","Mask","Mask of Many Faces","Mind","Mirror","Mist","Monkey","Moon","Mountain","Needle","Nerve","Night","Nightingale","Nightmare","Noise","Ocean","Octopus","Omen","One","Owl","Panther","Paragon","Pen","Phoenix","Piece","Pitch","Plant","Plough","Plume","Poison","Poison Cloud","Powder","Prism","Prison","Punch","Puppet","Queen","Quicksand","Raccoon","Rainstorm","Rat","Raven","Rhino","Right Hand","Ring","River","Robin","Rose","Sand","Scarecrow","Scorpion","Screen","Scythe","Sentinel","Serpent","Servant","Shadow","Shield","Shot","Slice","Smile","Snake","Snow","Song","Spark","Spear","Spell","Spider","Spirit","Spring Blossom","Star","Stitch","Storm","String","Sun","Sword","Talon","Teeth","Thorn","Throne","Thunder","Tiger","Titan","Tortoise","Tower","Trident","Turtle","Veil","Vessel","Viper","Virus","Visage","Vortex","Web","Whip","Wolf","Wolverine","Zone"];
var nm4 = ["Anaconda","Angel","Animal","Ape","Arm","Army","Aspect","Avalanche","Baboon","Badger","Bane","Basilisk","Bat","Beam","Bear","Beast","Beetle","Behemoth","Bell","Belt","Bird","Birth","Blade","Blizzard","Blood","Blossoms","Boa","Boar","Bolt","Bone","Book","Boulder","Branch","Breath","Bull","Burst","Candle","Canine","Cannon","Carriage","Cat","Chain","Champion","Charge","Chariot","Circle","Claw","Clock","Cloud","Clover","Cobra","Cocoon","Coil","Collar","Comet","Contract","Cord","Crab","Crane","Creature","Crescent","Cross","Crow","Crown","Curtain","Dance","Demon","Devil","Dimension","Disk","Dog","Doll","Dragon","Drum","Duo","Dust","Eagle","Elephant","Eye","Eyes","Falcon","Familiar","Fang","Fangs","Feast","Fist","Flame","Flesh","Flock","Flower","Force","Fork","Fox","Fruit","Gate","Gator","Ghost","Giant","Gift","Glove","God","Golem","Gorilla","Grace","Grip","Guard","Guardian","Guest","Halo","Hammer","Hand","Handle","Hare","Hawk","Heart","Hook","Hornet","Horror","Hound","Hunter","Hurricane","Ice","Image","Inferno","Insect","Jackal","Jaguar","Jaw","Jewel","Judge","Katana","King","Knife","Leaf","Leech","Leviathan","Lion","Locket","Locust","Mandrill","Mantis","Mask","Mist","Monkey","Moon","Mountain","Needle","Nightingale","Nightmare","Octopus","Owl","Panther","Paragon","Phoenix","Plant","Plough","Plume","Powder","Prism","Prison","Punch","Puppet","Queen","Raccoon","Rat","Raven","Rhino","Ring","River","Robin","Rose","Sand","Scarecrow","Scorpion","Screen","Scythe","Sentinel","Serpent","Servant","Shadow","Shield","Shot","Slice","Smile","Snake","Song","Spark","Spear","Spell","Spider","Spirit","Star","Stitch","Storm","String","Sword","Talon","Teeth","Thorn","Throne","Thunder","Tiger","Titan","Tortoise","Tower","Trident","Turtle","Veil","Vessel","Viper","Virus","Visage","Vortex","Web","Whip","Wolf","Wolverine","Zone"];

var br = "";

function nameGen(){
	var element = document.createElement("div");
	element.setAttribute("id", "result");
	
	for(i = 0; i < 10; i++){
		nTp = Math.random() * 4 | 0;
		rnd = Math.random() * nm1.length | 0;
		if(nTp < 3){
			rnd2 = Math.random() * nm3.length | 0;
			names = nm1[rnd] + " " + nm3[rnd2];
		}else{
			rnd2 = Math.random() * nm2.length | 0;
			rnd3 = Math.random() * nm4.length | 0;
			while(nm2[rnd2] === nm4[rnd3]){
				rnd3 = Math.random() * nm4.length | 0;
			}
			names = nm1[rnd] + " " + nm2[rnd2] + "-" + nm4[rnd3];
		}
		br = document.createElement('br');	
		element.appendChild(document.createTextNode(names));
		element.appendChild(br);
	}
	if(document.getElementById("result")){
		document.getElementById("placeholder").removeChild(document.getElementById("result"));
	}		
	document.getElementById("placeholder").appendChild(element);
}