function nameGen(type){
	var nm1 = ["Ãlvaro","Ãngelo","Ãmerson","Ãrico","Adriano","Agildo","Alberto","Alceu","Alessandro","Alexandre","Alfredo","AndrÃ©","AntÃ´nio","Antenor","Antonio","Armando","Arnaldo","Arnoldo","Arthur","Artur","Augusto","AurÃ©lio","BenÃ­cio","Benedito","Bernardo","Breno","Bruno","CÃ¡ssio","CÃ©sar","CÃ­cero","Caio","Carlos","CauÃ£","CauÃª","ClÃ¡udio","Cleiton","Conrado","Cristiano","Daniel","Danilo","Davi","Diego","Diogo","Douglas","Edgar","Edson","Eduardo","ElÃ­sio","Emanuel","Enrico","Erasmo","Eric","Escobar","EstevÃ£o","Evandro","FÃ¡bio","Fabiano","FabrÃ­cio","Felipe","Fernando","FlÃ¡vio","Francisco","Frederico","Gabriel","Geraldo","Gilberto","Gilmar","Gilson","Giovane","Guilherme","Gustavo","Heitor","Henrique","Hugo","Iago","Igor","IsaÃ­as","Ivanildo","Ivo","JÃºnior","JoÃ£o","Joaquim","Jonas","Jorge","JosÃ©","Juliano","Julio","Jurandir","KlÃ©ber","LÃºcio","Leandro","Leonardo","Lorenzo","Lucas","Luciano","Luiz","MÃ¡rcio","MÃ¡rio","Manoel","Manuel","Marcelo","Marcos","Mateus","MaurÃ­cio","Mauro","Michel","Miguel","Milton","Moacir","Murilo","Nelson","Neto","Nicolas","Nilton","Norberto","Oscar","Osmar","Osvaldo","OtÃ¡vio","Pablo","Paulo","Pedro","Rafael","Raul","Reginaldo","Reinaldo","Renan","Renato","Ricardo","Roberto","Rodolfo","Rodrigo","RogÃ©rio","Romeu","Ronaldo","SÃ©rgio","SÃ­lvio","Samuel","Sandro","Saulo","SebastiÃ£o","Sidnei","TÃºlio","Tadeu","Teodoro","Thiago","Tiago","TomÃ¡s","VÃ­tor","Valdomiro","Vicente","VinÃ­cius","Vinicius","Vitor"];
	ï»¿var  nm2 = ["Ãgata","Ãurea","Ãngela","Ãrica","Adelaide","Adriana","AlÃ­cia","Alana","Alcione","Alessandra","Alice","Aline","AmÃ©lia","Amanda","Ana","AndrÃ©ia","Andressa","AngÃ©lica","Anita","Antonieta","Ariane","Arlene","BÃ¡rbara","Beatriz","Benedita","Berenice","Betina","Bianca","Bruna","CÃ¡ssia","CÃ­ntia","Camila","Carina","Carla","Carolina","Caroline","Catarina","CecÃ­lia","ClÃ¡udia","Clara","Clarice","Clarissa","Cristiane","Cristina","DÃ©bora","Daiana","Daniela","Danila","Darcy","Denise","Diana","Edna","Eduarda","Elaine","Eliana","Elis","Elisa","Elisandra","Elizabete","EloÃ¡","EloÃ­sa","Elza","EmÃ­lia","EstefÃ¢nia","Estela","Ester","Esther","Evelyn","FÃ¡tima","FabÃ­ola","Fabiana","Fabiane","Fernanda","FlÃ¡via","Franciane","Francine","Gabriela","Giovana","Gisele","Gislaine","Helena","HeloÃ­sa","Heloisa","Hilda","Iara","InÃªs","Iolanda","Isabel","Isabela","Isadora","Ivete","Ivone","Izabel","JÃ©ssica","JÃºlia","JanaÃ­na","Janice","Jaqueline","Joana","Judite","Julia","Juliana","Julieta","Kelly","LÃ­via","LÃºcia","LaÃ­s","Larissa","Laura","LavÃ­nia","Leila","LetÃ­cia","Liana","Lorena","LuÃ­sa","LuÃ­za","Luana","Luciana","Lucielle","Luiza","MÃ¡rcia","MÃ´nica","Magali","Maiara","MaitÃª","Manoela","Manuela","MarÃ­lia","Marcela","Marcia","Maria","Mariana","Mariane","Marilsa","Marina","Marisa","Marlene","Marli","Marta","Matilde","Melissa","Michele","Milena","Mirela","Miriam","NÃ­vea","NatÃ¡lia","Neusa","Nicole","Nina","Odete","OlÃ­via","Olga","Paloma","Paola","PatrÃ­cia","Paula","Poliana","Poliane","Priscila","Rafaela","Raquel","Rebeca","Regina","Renata","Rita","Roberta","RosÃ¢ngela","Rosa","Rosana","SÃ­lvia","SÃ´nia","Sabrina","Samanta","Sandra","Sara","Sheila","Shirlei","Silvana","Simone","Sofia","Solange","Soraia","Suzana","TÃ¢nia","TaÃ­s","Talita","Tatiana","Teresa","Tereza","ThaÃ­s","VÃ¢nia","ValÃ©ria","Valentina","ValquÃ­ria","Vanda","Vanessa","Vanuza","VerÃ´nica","Vera","VirgÃ­nia","VitÃ³ria","Vivian","Wanda","Yasmin","Yolanda","ZÃ©lia","Zilda"];
	var nmf = ["Ãlvarez","Ãlves","Ãvila","Aguiar","Albuquerque","Alencar","Almeida","Alvarez","Alves","Amaral","AmbrÃ³sio","Amorim","Andrade","Antunes","AraÃºjo","Arruda","Assis","AssunÃ§Ã£o","Azevedo","Barbosa","Barreto","Barros","Barroso","Bastos","Batista","Belchior","Belluci","Bernardes","Bezerra","Bitencourt","Boaventura","Bonfim","Borba","Borges","Bosco","Braga","Branco","BrandÃ£o","Braz","Brito","Bueno","CÃ¢mara","Cabral","Caetano","Camargo","Campos","Canto","Cardoso","Carmo","Carvalho","Castilho","Castro","Cavalcanti","Cerqueira","Chagas","Chaves","Clemente","Coelho","ConceiÃ§Ã£o","Cordeiro","CorrÃªa","Correia","Costa","Couto","Cruz","Cunha","Damasceno","Delchiaro","Delgado","Dias","Duarte","Dutra","EspÃ­ndola","Esteves","Fagundes","FalcÃ£o","Farias","Fernandes","Ferraz","Ferreira","Figueiredo","Flores","Fonseca","Fontana","Fontes","Fraga","Freitas","Furtado","Garcia","Gimenes","Gomes","GonÃ§alves","Guedes","Guerra","GuimarÃ£es","Hamada","Hamamura","Hashimoto","Henriques","Higashi","Ito","Jardim","Jesus","Justino","Justo","Kanashiro","Kimura","LÃ³pes","Lacerda","Leal","LeitÃ£o","Leite","Lemos","Lima","Linhares","Lobo","Lopes","LourenÃ§o","Luz","Macedo","Machado","Maciel","Madruga","MagalhÃ£es","Maia","Maldonado","Mantovani","Marques","Martins","Matos","Medeiras","Medeiros","Medina","Meireles","Melo","Mendes","Menezes","Miranda","Monteiro","Moraes","Morais","Moreira","Moura","Nakamura","Nakata","Nascimento","NazÃ¡rio","Neves","Nogueira","Nunes","Oliveira","Pacheco","Padilha","Paim","Paiva","Paschoal","Passos","Paz","Pedroso","Pereira","Peres","Pessoa","Pimentel","Pinheiro","Pinho","Pinto","Pires","Prado","Prestes","Quadros","Queiroz","Quintana","Ramos","Reis","Rezende","Ribeiro","Rios","Rocha","Rodrigues","RosÃ¡rio","Rosa","Ruiz","SÃ¡","Salgado","Salles","Sanches","Santana","Santos","Saraiva","Sato","Serra","Serrano","Shinoda","Silva","Silveira","SimÃµes","Siqueira","Soares","Souza","Takeda","Tavares","Teixeira","Vale","Vargas","Vasconcelos","Vaz","Velho","Ventura","Vidal","Vieira","Vila","Watanabe","Ximenes","Yamada","Yoshimura","Zanetti"];
	var nmf2 = ["Ãlvarez","Ãlves","de Ãvila","Aguiar","de Albuquerque","Alencar","de Almeida","Alvarez","Alves","do Amaral","AmbrÃ³sio","Amorim","de Andrade","Antunes","AraÃºjo","Arruda","de Assis","de AssunÃ§Ã£o","de Azevedo","Barbosa","Barreto","Barros","Barroso","Bastos","Batista","Belchior","Belluci","Bernardes","Bezerra","Bitencourt","Boaventura","Bonfim","Borba","Borges","Bosco","Braga","Branco","BrandÃ£o","Braz","Brito","Bueno","CÃ¢mara","Cabral","Caetano","Camargo","de Campos","Canto","Cardoso","Carmo","Carvalho","Castilho","de Castro","Cavalcanti","Cerqueira","Chagas","Chaves","Clemente","Coelho","da ConceiÃ§Ã£o","Cordeiro","CorrÃªa","Correia","da Costa","Couto","da Cruz","da Cunha","Damasceno","Delchiaro","Delgado","Dias","Duarte","Dutra","EspÃ­ndola","Esteves","Fagundes","FalcÃ£o","Farias","Fernandes","Ferraz","Ferreira","Figueiredo","Flores","da Fonseca","Fontana","Fontes","Fraga","de Freitas","Furtado","Garcia","Gimenes","Gomes","GonÃ§alves","Guedes","Guerra","GuimarÃ£es","Hamada","Hamamura","Hashimoto","Henriques","Higashi","Ito","Jardim","de Jesus","Justino","Justo","Kanashiro","Kimura","LÃ³pes","Lacerda","Leal","LeitÃ£o","Leite","Lemos","de Lima","Linhares","Lobo","Lopes","LourenÃ§o","Luz","Macedo","Machado","Maciel","Madruga","MagalhÃ£es","Maia","Maldonado","Mantovani","Marques","Martins","de Matos","Medeiras","Medeiros","Medina","Meireles","Melo","Mendes","Menezes","Miranda","Monteiro","Moraes","Morais","Moreira","Moura","Nakamura","Nakata","do Nascimento","NazÃ¡rio","Neves","Nogueira","Nunes","de Oliveira","Pacheco","Padilha","Paim","Paiva","Paschoal","Passos","Paz","Pedroso","Pereira","Peres","Pessoa","Pimentel","Pinheiro","Pinho","Pinto","Pires","Prado","Prestes","Quadros","Queiroz","Quintana","Ramos","dos Reis","Rezende","Ribeiro","Rios","Rocha","Rodrigues","RosÃ¡rio","Rosa","Ruiz","SÃ¡","Salgado","de Salles","Sanches","Santana","dos Santos","Saraiva","Sato","Serra","Serrano","Shinoda","da Silva","Silveira","SimÃµes","da Siqueira","Soares","de Souza","Takeda","Tavares","Teixeira","do Vale","Vargas","Vasconcelos","Vaz","Velho","Ventura","Vidal","Vieira","Vila","Watanabe","Ximenes","Yamada","Yoshimura","Zanetti"];

	var tp = type;
	var br = "";
	var element = document.createElement("div");
	element.setAttribute("id", "result");
	
	for(i = 0; i < 10; i++){
		rnd2 = Math.random() * nmf.length | 0;
		rnd3 = Math.random() * nmf2.length | 0;
		while(rnd2 === rnd3){
			rnd3 = Math.random() * nmf2.length | 0;
		}
		if(tp === 1){
			rnd = Math.random() * nm2.length | 0;
			names = nm2[rnd] + " " + nmf[rnd2] + " " + nmf2[rnd3];
			nm2.splice(rnd, 1);
		}else{
			rnd = Math.random() * nm1.length | 0;
			names = nm1[rnd] + " " + nmf[rnd2] + " " + nmf2[rnd3];
			nm1.splice(rnd, 1);
		}
		nmf.splice(rnd2, 1);
		nmf2.splice(rnd3, 1);
		br = document.createElement('br');	
		element.appendChild(document.createTextNode(names));
		element.appendChild(br);
	}
	if(document.getElementById("result")){
		document.getElementById("placeholder").removeChild(document.getElementById("result"));
	}		
	document.getElementById("placeholder").appendChild(element);
}