ï»¿/* Belarus */
var nm1 = ["Ash","Asi","Ba","Bara","Bary","Bra","By","Bya","Byaro","Bye","Byelaa","Byera","Cha","Che","Chery","Da","Daro","Do","Dokshy","Dra","Drahi","Du","Dubro","Dzi","Dzuat","Dzyar","Fani","Ha","Hantsa","Hara","Hly","Hlybo","Ho","Hro","Iva","Ivatse","Ka","Kalin","Kamya","Kas","Kashal","Kastsyu","Kho","Khoy","Ki","Kira","Kli","Klima","Klye","Ko","Kosa","Kru","Kry","Laho","Li","Lue","Lunin","Lyak","Lyakha","Lyu","Ma","Mahi","Mala","Mi","Mika","Miyo","Mstsi","Mya","Naro","Nava","Navapo","Nova","Novalu","Nya","Or","Pasta","Pi","Pila","Pru","Pye","Pyetry","Raha","Re","Rechy","Sali","Shchu","Shklo","Ski","Slaw","Slo","Slu","Sma","Smalya","Sta","Sto","Svis","Svyet","Svyetla","Sya","Tala","Tu","Tura","Uz","Va","Valo","Vasi","Vasilye","Vawka","Vi","Vile","Vitsye","Vye","Vyer","Vyerhnya","Vyso","Ye","Za","Zaska","Zha","Zhabi","Zhlo","Zho","Zhod","Zhy","Zhyt","Zhytka"];
var nm2 = ["ban","bbokaye","bin","browna","brush","bruysk","bryn","btsy","chaw","chersk","chow","chyn","chytsa","da","dna","dok","dzina","dzyechna","dzyel","hachow","harad","hichyn","horsk","hoysk","ka","kavysk","kaw","kaye","khaw","ki","koml","kovichy","lach","lahorsk","latsk","lava","lawye","lin","lukoml","lya","lyow","myany","myel","nava","nim","nka","nkavichy","no","nsk","nyets","pal","pki","polatsk","povichy","pyel","pyl","rad","ran","raw","rhon","rki","roza","rsk","rudak","rush","ryta","sava","savichy","saw","sha","shniki","shytsy","slaw","sna","st","stavy","sty","sy","tka","tlava","trykaw","tsa","tsavichy","tsk","va","vichy","vinsk","vizh","vusy","vy","vyen","vysk","wka","wna","wye","ya","yavichy","ye","yebsk","yel","yets","yeyka","yory","yova","yow","zawka","zhany","zhyn","zhynsk","zino","zyechna","zyorsk","zyr"];
/* Czech Republic */
var nm3 = ["Å um","Å½a","BÅe","Bla","Bohu","Bole","Br","BudÄ","Che","Chomu","Chru","DÄ","FrÃ½","Ha","HavÃ­","HavlÃ­","Ho","Hodo","Hra","Hradi","Ja","Jablo","Ji","Jih","JindÅi","Jir","Kar","Kla","Klad","Ko","KopÅiv","Kop","Kr","Kro","KromÄ","Kut","LÃ­","Libe","Lit","Lito","LitvÃ­","Lou","MÃ­s","MÄl","Me","Mezi","Mla","Mo","NÃ¡","NÃ¡cho","No","Olo","Orlo","Ostra","Ostro","Ostroko","PÃ­","PÅÃ­","PÅe","Pa","Par","Pardu","Pl","Poa","Pra","Pro","ProstÄ","SÃ¡za","So","Soko","Stra","Strako","TÃ¡","TÃ¡bo","TÄ","TÅe","TÅi","Te","Tepli","Tru","Uher","Va","ValaÅ¡","Vala","Vse","VyÅ¡","Zno"];
var nm4 = ["ÄÃ­","ÄÃ­n","ÅÃ­ÄÃ­","ÅÃ­Å¾","Åice","Åov","Å¡Ã­n","Å¡tÄ","bÃ­Ä","bem","berec","bice","blonec","bor","bram","chÅ¯v","chod","clav","dÃ¡","dÅichÅ¯v","dek","dim","donÃ­n","dov","dubice","ha","humÃ­n","jov","jovice","kolov","konice","kov","kovice","lÃ­n","lava","lovÃ¡","lov","lovy","mÃ­n","mÄÅÃ­Å¾","mÄÅice","mo","mutov","nÃ¡","nÃ­k","nÃ­n","nec","nice","no","nov","ny","pa","pava","perk","plice","rec","rov","sek","skÃ©","sko","slav","sou","stÄjov","stek","tÃ­n","tec","tek","tov","tovy","vÃ¡","vÃ­Åov","vÃ­nov","vÃ½","va","vice","vinÃ¡","vou","vy","waldov","zavou"];
/* Hungary */
var nm5 = ["Ãjfe","Ãl","Abo","Aj","BÃ¡tony","BÃ©","Ba","Bal","Balas","Balaton","Balma","Beret","Bia","Biator","Bic","Bony","Bu","Buda","Budaka","Cell","Cson","Csor","Da","Do","Dom","Duna","Dunaha","Ede","GyÃ¶m","Gyomaen","Haj","HajdÃº","HajdÃºs","Hat","He","Isa","Isasz","JÃ¡sz","KÃ¶r","KÅs","Kalo","Kapu","Kar","Kazinc","Kere","Kesz","KisÃº","Kis","KiskÅ","Kiskun","Kista","KomÃ¡","Kom","Lajo","MÃ¡tÃ©","Ma","Mag","Mar","MezÅ","Mo","Nagy","Nagya","NyÃ­r","Oro","Orosz","PÃ¡","PÃ©","PÃ¼spÃ¶","Pa","Pi","Pilis","Po","RÃ¡","SÃ¡r","SÃ¡rbo","SÃ¡ro","SÃ¡to","SajÃ³","SajÃ³sz","Sar","SiÃ³","Sik","SzÃ¡zha","Szar","Szen","Szi","Szige","TÃ¶","TÃ¶rÃ¶k","Ta","Tapol","Tisza","Tol","VÃ¡r","VÃ¡rpa","Vec","Vere"];
var nm6 = ["bÃ¡gy","bÃ¡lint","bÃ¡tor","bÃ³vÃ¡r","barcika","bas","batta","berÃ©ny","bony","boszlÃ³","cag","cali","cel","cika","csa","dÃ¡ny","dÃ¶mÃ¶lk","daÃ¶rs","drÅd","dre","fÃ¶ldvÃ¡r","fÃ¼red","falu","fok","gÃ¡rd","glÃ³d","grÃ¡d","gy","gyarmat","hÃ¡cs","hÃ¡d","hÃ¡z","hÃ©rtÃ³","hadhÃ¡z","halas","jaÃºjhely","jhely","josmizse","kÃ¡llÃ³","kÃ¡ta","kÃ©cske","kÃ©s","kÃ³","kÃ¶l","kÃ¶vesd","kÅrÃ¶s","ka","kad","kalÃ¡sz","keszi","klÃ³s","kunhalas","kunmajsa","lÃ¡ny","lÃ¡s","lÃ¡sz","lÃ©ny","lÃ³","las","lca","lint","lis","lka","locsa","lom","lombatta","lota","mÃ¡z","mÃ¶lk","maendrÅd","majsa","mat","mend","miklÃ³s","nÃ¡nÃ¡s","nÃ¡s","na","nor","ny","palota","patak","pes","polca","puvÃ¡r","rÃ©ny","rÃ¶s","rÃ¶svÃ¡r","rÅ","raszti","red","renye","repes","rog","rom","ros","sÃ¡mson","sÃ©s","segyhÃ¡z","shÃ¡za","ske","smisze","son","tÃ¡d","tÃºr","ta","tak","tarcsa","tendre","terenye","tes","thalom","thely","ti","tirsa","tonfÃ¼red","tor","tvÃ¡r","vÃ¡r","vÃ¡rda","vÃ¡ri","vÃ¡ros","vÃ¶rÃ¶svÃ¡r","van","vas","vasvÃ¡ri","ve","ves","vesd","yÃ³Ãºjfalu","zÃºjvÃ¡ros"];
/* Moldova */
var nm7 = ["Èol","Ète","BÄl","Basa","Basara","Ben","Bi","Bri","Bu","Buco","CÄi","CÄlÄ","CÄu","Ca","Camen","Can","Cante","Cea","ChiÈi","Chi","Cimi","Co","Com","Cor","Corne","Coste","Cras","Cri","Crico","Criu","Criule","Cup","Dne","Dnes","Don","Dondu","Dro","Du","DubÄ","DubÄsa","Dur","Durle","Edi","FÄ","FÄle","Fru","Frun","Ghi","Ghin","Ghinde","Glo","Glode","Gri","Grigo","Grigorio","HÃ®n","HÃ®nce","Ia","Ialo","Ialove","Leo","Lip","Lipca","Lun","MÄr","MÄrcu","MÄrcule","Maia","Nis","Nispo","Ocni","Or","Ota","RÃ®È","RÃ®Èca","RÃ®b","RÃ®bni","Re","Rezi","SÃ®ng","SÃ®nge","SÃ®nger","Slo","Slobo","Soro","StrÄ","Ta","Tara","Te","Tele","Telene","Ti","Tira","Tvar","Un","Ung","Va","Vat","VulcÄ","VulcÄne"];
var nm8 = ["Èeni","Èi","ÈinÄu","Èlia","Èti","Èa","Èi","baesca","bozia","cÄneÈti","cani","ceÈti","ceni","chia","ci","cini","clia","covÄÈ","cova","dÄ","dÄr","deÈti","deni","der","diÈa","dru","duÈeni","dul","ga","gara","gera","gerei","gheni","hei","hul","leÈti","leni","lia","loveni","lul","menca","mir","nÄu","nÈa","na","nari","neÈti","neÈ","niÈa","ni","nii","noe","pol","poreni","raÈi","raclia","rat","reÈti","reni","ri","riopol","roca","ru","ruinÈa","sari","sca","spol","spolul","strovsc","teÈti","temir","vÄÈ","va","veni","zÄ","zia","zina"];
/* Poland */
var nm9 = ["ÅÃ³","Åo","Åom","ÅlÄ","ÅlÄs","ÅwiÄ","ÅwiÄtoch","Åwi","Åwid","Å»o","BÄd","BeÅ","BiaÅy","Bia","Biel","By","Byd","Che","Chor","CzÄs","CzÄsto","DÄ","DÄbro","EÅ","El","GÃ³r","GÃ³rni","GÅo","Gda","Gdy","Gli","Gliwi","Gnie","Gor","Gru","Grud","Ino","Inowro","Ja","Jastr","Jawo","Jawor","Jele","KÄd","KÄdzie","Ka","Kali","Kato","Kie","Kiel","Ko","Kosza","Kra","Leg","Legio","Lesz","Lu","Lub","Mie","MysÅo","Mys","No","Olsz","Opo","Os","Ostro","PÅo","Pa","Pabia","Pi","Pie","Pieka","Pio","Poz","Prusz","Prze","Przem","PuÅa","Pu","Ra","Raci","Rado","Radom","Ru","Ry","Ryb","Rzesz","SÅup","Sie","Siemia","So","Sosno","Sta","Stalo","Star","Stara","Su","Suwa","Szcze","Szczeci","Tar","Tarno","Tarnow","To","Toma","Toru","Try","Trybu","Ty","WÅo","WÅocÅa","WaÅ","War","Warsz","Wodzi","Wro","Za","Zamo","Zawie","Zgie","Zie"];
var nm10 = ["ÅÄka","Åa","Åawy","Åowice","Åystok","Å¼a","bÃ³rz","bianice","bie","bin","blÄg","browa","brzeg","brzych","bunalski","cÅaw","cÅawek","ca","chatÃ³w","chowa","chowice","chy","cie","cin","dÅº","daÅsk","da","domsko","gÃ³w","gard","goszcz","kÃ³w","kary","kie","krzyski","la","laska","le","lec","lenia","lin","lisz","lona","lowa","mÅ¼a","myÅl","nÃ³w","naÅ","nia","nica","nice","nicza","nik","nin","nowice","nowiec","nowo","ruÅ","ry","ska","skie","sko","stok","tÃ³w","tom","tyn","waÅki","wa","wek","wice","wiec","worzno","wrocÅaw","wy","zÃ³w","zÄbie","ziÄdz","zierzyn","zin","zno","zyn"];
/* Romania */
var nm11 = ["Ãnsu","Ãntor","Èim","Èom","Ète","ÈÄn","Èic","Ad","Agni","Ama","Ani","Ar","Azu","BÃ¢r","BÄ","BÄi","BÄile","BÄl","BÄnea","Ba","Baba","Be","Ber","Bere","Bi","Bistri","Bo","Bolde","Bolin","Bor","Boto","BrÄi","Bra","Braga","Bre","Brea","Bro","BuÈte","Bu","Buce","Bucha","Bude","Buf","Buhu","Bumbe","CÄlÄ","CÄla","CÄli","CÄlimÄ","CÄzÄ","Ca","Caj","Cala","Cara","Caranse","Cav","Cerna","ChiÈi","Chi","Chiti","Cia","Ciaco","Cis","CisnÄ","Cod","ComÄ","Comar","Constan","Cop","Cora","Coste","Cova","Cri","Cristu","Cur","Curti","DÄbu","DÄrmÄ","Dara","De","Dolha","Doro","DrÄgÄ","Drago","Dro","Drobe","DumbrÄ","Efo","FÄ","FÄgÄ","FÄlty","FÄu","Fete","Fie","Fier","Fierbi","Filia","FlÄmÃ¢","Foc","Fra","Fundu","GÄe","Gala","Gher","Ghim","Giur","HÃ¢r","Ha","Hore","Hu","Hue","Hune","Ian","Ier","Ji","Jim","Jimbo","Li","Lipo","Liva","Lu","MÄ","MÄgu","MÄrÄ","Manga","Me","Medgi","Mier","MihÄi","Mili","Mio","Mo","Moi","More","Mur","NÄ","NÄd","NÄvo","Nova","Odo","Odor","Olte","One","OrÄ","Ora","Oravi","Oto","Ovi","PÃ¢n","PÄtÃ¢r","Pa","Pan","Pante","Peci","Petri","Petro","Pia","Pogoa","Pre","Pucioa","RÃ¢","RÃ¢ca","RÃ¢dÃ¢u","RÃ¢mni","Re","Reca","RoÈio","Rovi","SÃ¢","SÃ¢li","SÃ¢n","SÃ¢rma","Salon","Sega","Sime","Sla","Slobo","Sova","Stre","Suli","TÄl","TÄlma","Techir","Tecu","Timi","Tisma","Topo","Topolo","Tur","Uri","Urica","Urzi","Vico","Vide","Volun","ZÄrne","Za","Zimni","Zla"];
var nm12 = ["ÈÄuÈi","Èa","Èani","ÈiÈa","Èi","Èineu","Èoara","Èov","Èova","Èteni","Èti","Ètie","Èei","badag","bani","bav","beÈ","beÈti","beni","biÈ","bia","binÈi","biu","bolia","bou","bozia","cÄu","cal","cani","cari","caz","ceÈti","cea","ceava","cecea","ceni","chet","ci","ciu","clean","coi","cota","cova","curea","cuta","dÄrei","dÄuÈi","dari","deÈti","dele","dia","din","diru","diu","doara","dud","gÄraÈ","galia","gele","geni","gheni","ghiol","ghita","gidia","giu","gu","hasca","hiÈa","hoi","huÈi","lÄu","laÈi","la","lac","lad","lafat","lagele","lan","leÈti","lean","leni","leu","liÈa","lia","lina","lintin","lonta","loveni","lui","lung","mÄneÈti","maÈu","mana","mara","meni","mireÈti","mos","nÄdie","nad","naia","neÈti","neasa","niÈa","ni","nic","nicea","nicu","niei","nina","nita","noasa","nut","peni","pova","rÄÈei","raÈ","raÈi","ra","racal","rad","raolt","reÈti","rei","rele","reni","rest","rezu","riÈa","ria","rie","rig","rila","robia","rohoi","rud","sÄud","sebeÈ","sec","sna","sura","tari","tea","teni","ticeni","tila","tin","tina","triÈa","trila","turu","vaci","vada","vana","vaniei","vasna","vata","veni","viÈa","vodÄ","zÄu","za","zia","zoi","zu"];
/* Slovakia */
var nm13 = ["Äad","Äier","Å aÅ¡","Å a","Å amo","Å tÃº","Å u","Å ura","Å½ar","Å½arno","Å½e","Å½el","Å½elie","Å½i","Å½ia","Å½il","Å½ili","BÃ¡","BÃ¡no","Ban","Bar","Barde","Boj","Bra","Bratis","Brez","Brezo","Byt","Det","Dob","Dol","Du","Dud","Dudin","Duna","Dunaj","Gbe","Gbel","Gel","Gi","Gira","Giral","Hand","Hanu","Hlo","Hloho","HnÃº","Ho","Hri","Hu","Humen","Hur","Hurba","Ila","Jel","KeÅ¾","KoÅ¡","Ko","KolÃ¡","Kol","KomÃ¡","Kom","KrÃ¡","KrÃ¡s","Krem","Krom","Kru","Ky","Le","Leo","Leopol","Levi","Levo","Li","Lip","Lipa","LuÄe","Lu","Mal","Mala","Mar","Med","Medzil","Mi","Micha","Mo","Mod","Mol","Molda","My","Myja","NÃ¡","NÃ¡me","Nem","Ni","PÃº","Par","Parti","Pezi","PieÅ¡","Podo","Pol","Pop","PovaÅ¾","Pova","PreÅ¡","Pre","Prie","Prievi","Ra","Re","RevÃº","Rima","RoÅ¾","RuÅ¾o","RuÅ¾om","Sabi","SeÄo","SeÄov","Se","Sene","Seni","Ska","SlÃ¡d","SlÃ¡dko","Sni","So","Sobra","SpiÅ¡","Sta","StrÃ¡Å¾","StrÃ¡","Strop","Stu","Stupa","SvÃ¤","Svi","Svid","Ti","Tiso","Tlma","Topo","Tor","Tre","Trebi","Tren","Trna","Trste","Tur","VrÃ¡","VrÃº","VrÃºt","Vra","Vran","Vy","Vyso","Zla","Zvo"];
var nm14 = ["ÄÃ­n","Äa","Äovo","Åava","ÅovÃ¡","Å¡Ã­n","Å¡ava","Å¡ice","Å¡inÃ¡","Å¡ovÃ¡","Å¡ov","Å¡ovce","Å¡ta","Å¾e","Å¾ske","bÃ­n","berok","binov","borce","ca","chov","dava","dejov","dince","dov","drÃ½","dra","hovec","hy","java","jec","jeckÃ©","jov","kÃ©","kov","kovo","ky","lÃ­Ä","lÃ­nec","lacky","lanta","lava","len","lica","lina","lom","lovÃ¡","lovce","ly","mÃ¡rno","marok","morÃ­n","nÃ¡","nÃ©","nÃ­k","nÃ½","na","nec","nica","no","nok","nov","novce","novica","novo","ny","pachy","pany","pava","pina","poldov","rÃ­n","rad","rance","rany","red","rica","rok","rovo","skÃ¡","skÃ½","stovo","suckÃ©","tÃ¡r","tÃ­n","ta","tin","tovce","tra","vÃ¡","vÃ©","vÃºca","va","vce","vec","viÄovo","vica","vice","vidza","voÄa","vo","vou","zÃ¡nske","zev","zinok","zovÃ¡","zovce"];
/* Ukraine */
var nm15 = ["Advii","Al","Alche","Alma","Alu","Amvro","Anan","Andru","Antra","Apo","Aposto","Armia","Arte","Artemi","Bakh","Bal","Bala","Bara","Barvin","Batu","Ber","Berdy","Bere","Bery","Bil","Bilo","Bobro","Boho","Bole","Bor","Bory","Bro","Bu","Cher","Cherno","Cherny","Chervo","Chort","Chu","Debal","Der","Derazh","Dnipro","Dobro","Doku","Doly","Droho","Druz","Dubrov","Dunai","Dymy","Dzer","Dzhan","Ener","Fas","Hai","Haivo","Heni","Her","Hir","Hlo","Hlu","Horliv","Horo","Hre","Illi","Ilo","Inker","Ir","Izia","Kaha","Kakho","Kalu","Kaly","Kamia","Karli","Khar","Khmil","Kho","Khor","Khy","Kiro","Kiver","Kobel","Kolo","Komso","Kono","Koriu","Koro","Koto","Kozia","Krama","Krasno","Krasnoa","Krasy","Kreme","Krole","Kurak","Kuznet","Lani","Lebe","Liu","Lozo","Luha","Lutu","Lypo","Lysy","Mar","May","Meli","Mere","Miu","Molo","Mona","Mor","Mosty","Muka","Myko","Myr","Nad","Nemy","Niko","Nosi","Novoa","Novomo","Novou","Ocha","Orik","Ostro","Pere","Pervo","Pid","Polo","Pomi","Pry","Pryvi","Pusto","Rade","Rado","Rava","Rodyn","Rom","Roven","Roz","Rubi","Rzhy","Sam","Sar","Sely","Semeni","Sere","Sevas","Shar","Shepe","Shos","Sievero","Sim","Simfero","Ska","Skado","Sla","Slo","Sni","Snia","Soky","Sole","Staro","Storo","Sudo","Sva","Sver","Svia","Svit","Syne","Tara","Tatar","Tavri","Teplo","Tere","Terni","Tia","Tros","Tur","Ulia","Uzh","Val","Vash","Vasy","Vatu","Verkhi","Vil","Volo","Vov","Vozne","Vuhle","Vyno","Vysh","Yaho","Yare","Yavo","Yena","Zapor","Zasta","Zba","Zbo","Zdol","Zeleno","Zhda","Zhmer","Zho","Zhyda","Zhyto","Zo","Zolo","Zon","Zuh","Zveny","Zymo"];
var nm16 = ["binka","botyn","bunary","bych","byl","byne","chach","chaiv","chansk","chesk","chevo","chevsk","chiv","chuk","chyn","darsk","denka","diach","diansk","dilna","dilsk","divka","dok","doriv","driia","drivsk","dy","dyma","dysche","hachi","hanov","hatyn","hirsk","hodar","horod","hove","hovka","huiv","hyne","hyryn","ka","kasy","khiv","khove","kine","kiv","kivka","kliia","kopsk","kove","koy","kva","laiv","liaky","liany","livka","lodar","love","lych","lyk","lyna","lynsk","lynska","lytsia","mach","man","marno","mazna","mivsk","morsk","move","myia","myshl","nets","nia","niany","nihiv","nivka","nobyl","nohrad","nov","nyk","pillia","pole","rad","riv","rivka","rod","rodok","romyl","ropol","rovsk","ruch","rudne","ryn","ryska","saray","schiv","seve","shad","shivka","shta","shyn","siivka","siya","ske","slav","son","sovsk","spil","spyne","stiv","stopol","syt","syzk","ta","tanka","tarsk","tava","techko","tivka","topol","torsk","trov","tyn","tyvl","vaisk","valsk","van","vary","vodsk","vodske","vohrad","vuta","vutych","vylib","vytsia","yi","yiv","zan","zansk","zerske","zhany","zhyn","zhynets","zhynsk","zivka","zna","zne","zova","zovsk"];

var br = "";

function nameGen(){
	var element = document.createElement("div");
	element.setAttribute("id", "result");
	
	for(i = 0; i < 16; i++){
		if(i < 2){
			rnd = Math.floor(Math.random() * nm1.length);
			rnd2 = Math.floor(Math.random() * nm2.length);
			names = nm1[rnd] + nm2[rnd2];
		}else if(i < 4){
			rnd = Math.floor(Math.random() * nm3.length);
			rnd2 = Math.floor(Math.random() * nm4.length);
			names = nm3[rnd] + nm4[rnd2];
		}else if(i < 6){
			rnd = Math.floor(Math.random() * nm5.length);
			rnd2 = Math.floor(Math.random() * nm6.length);
			names = nm5[rnd] + nm6[rnd2];
		}else if(i < 8){
			rnd = Math.floor(Math.random() * nm7.length);
			rnd2 = Math.floor(Math.random() * nm8.length);
			names = nm7[rnd] + nm8[rnd2];
		}else if(i < 10){
			rnd = Math.floor(Math.random() * nm9.length);
			rnd2 = Math.floor(Math.random() * nm10.length);
			names = nm9[rnd] + nm10[rnd2];
		}else if(i < 12){
			rnd = Math.floor(Math.random() * nm11.length);
			rnd2 = Math.floor(Math.random() * nm12.length);
			names = nm11[rnd] + nm12[rnd2];
		}else if(i < 14){
			rnd = Math.floor(Math.random() * nm13.length);
			rnd2 = Math.floor(Math.random() * nm14.length);
			names = nm13[rnd] + nm14[rnd2];
		}else{
			rnd = Math.floor(Math.random() * nm15.length);
			rnd2 = Math.floor(Math.random() * nm16.length);
			names = nm15[rnd] + nm16[rnd2];
		}
		br = document.createElement('br');	
		element.appendChild(document.createTextNode(names));
		element.appendChild(br);
	}
	if(document.getElementById("result")){
		document.getElementById("placeholder").removeChild(document.getElementById("result"));
	}		
	document.getElementById("placeholder").appendChild(element);
}