var nm1 = ["Ãlvaro","Ãngel","Ãdgar","Ãliver","Ãscar","AarÃ³n","Aaron","Abel","Abraham","Abram","AdÃ¡n","AdriÃ¡n","AgustÃ­n","Alan","Alberto","Alejandro","Alex","Alexander","Alexis","Alfonso","Alfredo","Alonso","Alonzo","AndrÃ©s","Angel","Anthony","Antonio","Armando","Arturo","Axel","Bautista","Benito","BenjamÃ­n","BernabÃ©","Bruno","CÃ©sar","Camilo","Carlos","Carmelo","Christian","Christopher","CristÃ³bal","Cristian","DÃ­dac","DamiÃ¡n","Daniel","Dante","David","Diego","Diego Alejandro","Domingo","Dylan","Edmundo","Eduardo","Efraim","Efrain","ElÃ­as","Eliseo","Emanuel","Emiliano","Emilio","Emmanuel","Enrique","Erick","Ernesto","Esteban","Estefania","Eustacio","Ezequiel","FabiÃ¡n","Facundo","Felipe","Felix","Fernando","Francisco","Franco","Gabriel","Gael","Gerardo","Gonzalo","Guillermo","Gustavo","HÃ©ctor","Hector","Hugo","Ian","Ignacio","Iker","InhuÃ©","IsaÃ­as","Isaac","Isidoro","Ismael","Israel","IvÃ¡n","Ivan","Jacobo","Jaime","Jairo","Javier","JerÃ³nimo","JeremÃ­as","JesÃºs","Jesus","JoaquÃ­n","Joaquin","Joel","JonatÃ¡n","Jonathan","Jorge","JosÃ©","Jose","Joshua","JosuÃ©","Juan","Juan AndrÃ©s","Juan David","Juan Diego","Juan Esteban","Juan JosÃ©","Juan Manuel","Juan MartÃ­n","Juan Pablo","Juan SebastiÃ¡n","Juanita","JuliÃ¡n","Julian","Julio","Justin","Kevin","Kimberly","Lautaro","Leonardo","Lorenzo","Luca","Lucas","Lucho","LuciÃ¡n","Luciano","Luis","Luz","MÃ¡ximo","Macos","Manuel","Marco","Marcos","Mariano","Mario","MartÃ­n","Martin","MatÃ­as","Mateo","Matthew","Mauricio","Max","Maximiliano","Miguel","Miguel Ãngel","Milagros","Moises","Nico","NicolÃ¡s","Orlando","Oscar","PaÃºl","Pablo","Pascual","Patricio","Pedro","Primitivo","RaÃºl","Rafael","RamÃ³n","Ramon","Raul","Ricardo","Rigoberto","Roberto","Rodrigo","Rolando","RomÃ¡n","RubÃ©n","SaÃºl","Salvador","Samuel","Santiago","Santino","SebastiÃ¡n","Sebastian","SerafÃ­n","Sergio","SimÃ³n","Stefano","Thiago","TobÃ­as","TomÃ¡s","Tomas","Umberto","VÃ­ctor","ValentÃ­n","Valentino","Vicente","Xavier","ZacarÃ­as"];
var nm2 = ["Ãngela","Ãngeles","Abigail","Abril","Ada","AdoraciÃ³n","Adriana","Agustina","Aitana","Alana","Alba","Albina","Alejandra","Alessandra","Alexa","AlexandrÃ­a","Alexandra","Alexia","Alexis","Alicia","Alina","Allison","Alma","Amanda","Amaya","Amelia","Ana","Ana MarÃ­a","Ana Paula","Ana SofÃ­a","Ana Sofia","Andrea","AngÃ©lica","Angela","Angelina","Antonella","Antonia","Araceli","Ariadna","Ariana","Ashley","Asia","AsunciÃ³n","Aurora","BÃ¡rbara","Bella","Bianca","Brenda","Briana","Brisa","Camila","Candela","Carina","Carla","Carmen","Carolina","Catalina","Catarina","Cecilia","Celeste","Clara","Claudia","ConcepciÃ³n","Constanza","Consuela","Covadonga","Cristina","DÃ©bora","Daniela","Daniella","Delfina","Diana","Doria","Dulce","Eduarda","Elena","Eliana","Elisa","Elisabet","Elisenda","Elizabeth","Elsa","Emanuella","Emilia","Emily","Emma","EncarnaciÃ³n","Engracia","Esmeralda","Esperanza","Estela","Estrella","Eva","Evangelina","FÃ¡tima","Fabiana","Fatima","Felipa","Fernanda","Florencia","Frida","GÃ©nesis","Gabriela","Giuliana","Gloria","Graciela","Guadalupe","Hermosa","Ines","Inmaculada","Irene","Iris","Isabel","Isabela","Isabella","Isaias","Isidora","Ivanna","Jauna","JazmÃ­n","Jimena","Josefa","Josefina","Juana","Juanita","Julia","Juliana","Julieta","LÃ­a","Laura","Laura SofÃ­a","Leila","Lila","Lilian","Liliana","Linda","Lola","Luana","LucÃ­a","Lucia","Luciana","Luisa","Luna","MÃ­a","MÃ³nica","Magdalena","Maite","Malena","Manuela","MarÃ­a","MarÃ­a Alejandra","MarÃ­a Camila","MarÃ­a Fernanda","MarÃ­a JosÃ©","MarÃ­a Paula","Marcela","Margarita","Maria","Maria JosÃ©","Mariana","Mariangel","Marina","Marisa","Marisol","Marta","Martina","Maya","Melanie","Melina","Melissa","Mercedes","Mia","Micaela","Michelle","Miranda","Miriam","Monserrat","Montserrat","Morena","NaomÃ­","Natalia","Natalie","Nazarena","Nazaret","Nicole","Nina","NoÃ©","Nora","Octavia","Olivia","Paloma","Paola","Pastora","Patricia","Paula","Paulin","Paulina","Paz","PenÃ©lope","Perla","Pilar","Priscila","Rafaela","Raquel","Rebeca","Regina","Renata","Rene","Romina","Rosa","Rosario","Rubi","Sabrina","SalomÃ©","Samantha","Sandra","Sara","Sara SofÃ­a","Selena","Serena","Silvana","SofÃ­a","Sofia","Soledad","Sophie","Stephanie","Susana","TalÃ­a","Tatiana","Teresa","Tia","Valentina","Valeria","Valerie","Valery","Vanessa","VerÃ³nica","Veronica","Victoria","Violeta","Virginia","Vivian","Viviana","Ximena","Ximena","Yesenia","Yolanda","Yvonne","Zarina","Zoe"];
var nm3 = ["Ãguila","Abasto","AbellÃ¡n","Agramonte","Aguayo","Aguinaldo","AlarcÃ³n","AlcabÃº","Alcocer","AlemÃ¡n","Alguacil","Alvarado","Amengual","Andino","Andrade","Aparicio","Arboleda","Arias","Arnal","Arrabal","Atenas","Barrios","Barrueco","Beldad","Berganza","Berrocal","Bienvenida","BotÃ­n","CÃ©spedes","Cabal","Cadaval","Cambeiro","Campos","Capmany","Carballal","Carballar","Carballo","Carita","Carvallo","Casaus","Cazalla","Chicote","CicerÃ³n","Collazo","Coronil","Correa","CortÃ©s","Costa","Cotilla","Covarrubias","Curbelo","DÃ¡valos","Dengra","Elvira","EncarnaciÃ³n","Escribano","Espiga","Espina","Espinar","Feijoo","FernÃ¡n","Fernandino","Ferrant","Figueroa","Fonseca","Fontirroig","Fraga","Franco","Freixa","GÃ¡lvez","GalÃ¡n","Gallo","Gaona","Gaos","GarcÃ­a","Garrido","Gayoso","Gilabert","Gisbert","GonzÃ¡lez","Graciani","GuillÃ©n","GutiÃ©rrez","Hurtado","Illescas","Indiano","JapÃ³n","JuderÃ­as","LÃ³pez","Lacasa","Laguna","Lain","Leguizamo","Leoz","Luque","Madrid","Magrina","Mancebo","Manzanares","Manzanedo","Mariano","Maroto","MartÃ­","MartÃ­nez","Mastache","Mina","Miralles","Molina","Montenegro","Montes","Montreal","Morillo","Morterero","Moruga","Moya","MuÃ±oz","Murillo","Navarro","Noboa","Nores","ObregÃ³n","Ocampo","OrdÃ³Ã±ez","Palacio","Palau","ParÃ­s","Pardo","Pareja","PiÃ±Ã³n","Pinto","Pliego","Pomar","Pousa","Pozo","Prats","Puig","Quesada","Rasgado","Reyes","RodrÃ­guez","Romero","Ros","Rouco","Rubio","Ruiz","SÃ¡enz","SÃ¡ez","SÃ¡nchez","Saavedra","Saelices","Sainz","San MartÃ­n","Sancho","SantÃ¡ngel","Sanz","Sarmiento","Secada","Seco","SemprÃºn","Tafalla","Tamayo","Tasis","Tassis","Tejedor","Tenorio","UreÃ±a","Valerio","Varela","VelÃ¡zquez","Venegas","Vera","Villa","VillacrÃ©s","Xirau","Yepes","Zoido","Zorita","de la CavallerÃ­a","de la Cruz","del Pozo"];

function nameGen(type){
	var tp = type;
	var br = "";
	var element = document.createElement("div");
	element.setAttribute("id", "result");
	
	for(i = 0; i < 10; i++){
		rnd2 = Math.floor(Math.random() * nm3.length);
		if(tp === 1){
			rnd = Math.floor(Math.random() * nm2.length);
			names = nm2[rnd] + " " + nm3[rnd2];
		}else{
			rnd = Math.floor(Math.random() * nm1.length);
			names = nm1[rnd] + " " + nm3[rnd2];
		}
		br = document.createElement('br');	
		element.appendChild(document.createTextNode(names));
		element.appendChild(br);
	}
	if(document.getElementById("result")){
		document.getElementById("placeholder").removeChild(document.getElementById("result"));
	}		
	document.getElementById("placeholder").appendChild(element);
}