var br = "";

function nameGen(type){
	var tp = type;
	var nm1 = ["Äedo","Äeka","ÄorÄije","Äukan","Äuko","Äulja","ÄuraÄ","Äuran","Äuro","Å Äepan","Å ako","Å akota","Å aleta","Å oro","Å piro","Å ujo","Å uto","Å½arija","Å½arko","Å½elidrag","Å½ivko","Advan","Akso","Ananije","Andro","Anto","Arsenije","Arso","BaÄo","BaÅ¡o","Bajo","BakoÄ","Bako","BalÅ¡a","Banjo","Bato","BatriÄ","BeÄo","BlaÅ¾ija","BlaÅ¾o","BlagoÅ¡","Blagota","BoÅ¾ina","BoÅ¾o","Bodin","BogiÄ","Boro","BrajuÅ¡ko","Brano","Budo","Crnoje","Danilo","Danko","Davor","Diko","Dinjo","Dmitar","Dobrilo","Dobrislav","DojÄilo","DraÅ¡ko","DragiÅ¡a","Dragoje","Dumelja","Emilo","GaÅ¡o","Gajo","Gavro","Gligor","Gojak","Gojislav","Gojko","Golub","GorÄilo","GorÄin","Grgur","Grujica","Ignjatije","Iliko","Ilko","Isailo","Ivan","Iveza","Jablan","JagoÅ¡","JakÅ¡a","Janko","Jevrem","Joko","Joksim","Jole","Jolje","JovaÅ¡","Joveta","Kenjo","KiÄun","Kiro","KoÄa","Komlen","Komnen","Krcun","Krsto","Labud","Lagota","Laketa","LakiÄ","Lakota","Lale","Latko","Leka","Ljubeta","Luka","MaÅ¡an","MaÅ¡o","MaÅ¡ut","Maksim","Maljota","MarkiÄ","MarkiÅ¡a","Matan","Matija","MiÄa","MiÄun","Mihajilo","Mijat","Mijo","MijuÅ¡ko","Mikailo","Mikan","Miketa","Mikonja","Mikosav","Mikota","MilaÅ¡in","Miladin","Mile","Mileta","MiliÄ","Milija","Milivoje","Milo","Miloje","Milonja","Milun","Milutin","Miomir","MirÄeta","MiraÅ¡","Mirko","Mirkota","Miro","Miroje","Mirun","MojaÅ¡","Mojsija","Mojsije","Momir","MrÄen","Mrdelja","Mrgud","Mrkonja","Mrkota","Murgeza","Najdan","NeÄeljko","Nenoje","NikÅ¡a","Nikac","Nikola","NjegoÅ¡","Novak","Novelja","Novica","Novo","Obren","Orle","Pajo","Panto","PeÅ¡a","PejÄin","Pejo","Peko","PeriÅ¡a","Perko","Perovan","Petko","PetraÅ¡in","Predivoje","Prele","Prelja","Premo","PuÅ¡elja","PuniÅ¡a","Puren","RaÅ¡ko","Radan","Radava","RadiÅ¡a","Radivoje","RadoÅ¡","Radoje","Radonja","Radosav","Radoslav","Radovan","Radul","Radule","Radun","Rajko","Rako","Ristan","Risto","Rogan","Savan","SaviÄ","Sekule","SiÄo","Simo","Simon","Srdan","Sreten","Sreto","Sretomir","Stijepo","Stracimir","Strado","TadiÅ¡a","Tadija","Tate","ToÅ¡an","Todor","TomaÅ¡","Tomo","Tripun","Turo","UgljeÅ¡a","Valtazar","Vasilije","Vasilj","Vasko","VeÅ¡o","VeliÅ¡a","Velisav","Velizar","Veljo","Vesko","Veso","Vicko","Vidak","Vidan","Vido","Vidoje","Vilko","Vitomir","Vladimir","Vojin","Vojo","VuÄeta","VuÄiÄ","VuÄidar","VuÄina","VuÄo","VuÅ¡ur","VujaÅ¡","Vujadin","Vujan","Vujica","VukaÅ¡in","Vukadin","Vukajlo","Vukale","VukiÄ","Vukislav","Vukojica","Vukola","Vukoman","Vukomir","Vukosav","Vukota","Vuksan","Vule","Vuleta","Zaharija","Zarija","Zaro","Zejo","Zeko","Zelen","Ziroje","Zrno"];
	var nm2 = ["ÃurÄa","Äetna","Äeda","Äedomila","Äekna","Äina","ÄorÄina","ÄurÄina","Ada","AnÄe","Anka","Birka","Bojana","Borka","Bosa","Buda","Budimirka","Bula","Cmiljana","Danojla","Dara","Darinka","Dokna","Draga","Dragica","Draginja","DuÅ¡anka","DuÅ¡ka","DuÅ¡na","Dubravka","Dunja","Ema","Femija","Gara","Gina","Gojislava","Gora","Gorana","Gorde","Gorka","Gospava","Grana","Granica","Groja","Grozdana","Ikonija","Ilinka","Ilosava","Jadranka","Janica","Janja","Jela","Jelika","Jelka","JoÅ¡ana","Joka","Jova","Julka","KiÄa","Kokna","Kosa","Kosara","Koviljka","Krstinja","Ljeposava","Lucija","Lutka","Manda","Mara","Marta","MiÅ¡nja","MiÅ¡ur","Mila","Milanka","Milijana","Milja","Miljka","MiljuÅ¡a","Milojka","Milosava","MiluÅ¡a","Milunka","Mioljka","Mirela","Mirosava","MiruÅ¡a","Miruna","Mitra","Mladija","Njegosava","Novka","Obrenija","Pavka","Pejka","Pelivanka","Perka","Persa","Petra","Petrana","PetruÅ¡a","Plana","Poleksija","Radana","Radojka","RaduÅ¡a","Raka","Rosa","Rumica","Savka","SinÄa","Soka","Solumija","Velika","Velinka","Veselinka","Vida","Vidna","Vidosava","Vidra","Vinka","Vjera","Vukalica","Zagorka","Zorka","Zorna"];
	var nm3 = ["ÄetkoviÄ","Äabarkapa","ÄarapiÄ","ÄelebiÄ","ÄuroviÄ","ÄakonoviÄ","ÄikanoviÄ","Äilas","ÄokoviÄ","ÄorÄeviÄ","ÄukanoviÄ","ÄuriÄ","ÄuriÄiÄ","ÄuriÅ¡iÄ","ÄuroviÄ","Å ÄepanoviÄ","Å abanadÅ¾oviÄ","Å aranoviÄ","Å ehoviÄ","Å evaljeviÄ","Å iljak","Å obiÄ","Å ukoviÄ","Å½iÅ¾iÄ","Å½ivkoviÄ","AlibabiÄ","AndrijaÅ¡eviÄ","Antonije","AsanoviÄ","BaÅ¡a","BaÅ¡iÄ","BakiÄ","BaliÄ","BarjaktaroviÄ","BaroviÄ","BeÄanoviÄ","Berkuljan","Bjelica","BjelogrliÄ","BlagojeviÄ","BoÅ¡koviÄ","BoÅ¾oviÄ","BojaniÄ","BoljeviÄ","Borisov","Borozan","BrajoviÄ","Brguljan","BrkoviÄ","BujoviÄ","BulajiÄ","BulatoviÄ","BuliÄ","BuniÄ","BuriÄ","Burzan","CeroviÄ","CrnojeviÄ","Damjanac","DamjanoviÄ","DapÄeviÄ","DeliÄ","DemiroviÄ","DoÅ¾iÄ","DobraÅ¡inoviÄ","DraÅ¡koviÄ","DragojeviÄ","DragoviÄ","DrinÄiÄ","DrljeviÄ","Drobnjak","DubljeviÄ","Faddy","FatiÄ","FilipoviÄ","Gajda","GajoviÄ","GojkoviÄ","GvozdenoviÄ","HadÅ¾iosmanoviÄ","HajdukoviÄ","HakÅ¡abanoviÄ","HuseinoviÄ","IliÄ","IvaniÅ¡eviÄ","IvanoviÄ","IvoviÄ","JankoviÄ","JanoviÄ","JaukoviÄ","JovanoviÄ","JovetiÄ","JovoviÄ","KaleziÄ","KaluÄeroviÄ","KanaceviÄ","KankaraÅ¡","KapiÄiÄ","Kapisoda","KaradÅ¾iÄ","KaradagliÄ","KavariÄ","Kilibarda","Klikovac","Klimenta","KneÅ¾eviÄ","Kokolja","KomneniÄ","KovaÄ","KovaÄeviÄ","KoviniÄ","KraljeviÄ","KrivokapiÄ","KrstajiÄ","KujoviÄ","LaboviÄ","LaliÄ","LambuliÄ","LazoviÄ","Lipovina","LjubiÅ¡a","Lompar","Lubarda","LukÅ¡iÄ","Malkovich","MandiÄ","MaraÅ¡","MarkoviÄ","MaroviÄ","MartinoviÄ","MaruÅ¡iÄ","Maskareli","MedvidoviÄ","MehmedoviÄ","Mihailo","MijatoviÄ","MijuÅ¡koviÄ","MiljaniÄ","MilunoviÄ","MirotiÄ","MrvaljeviÄ","MugoÅ¡a","MuratoviÄ","NikÄeviÄ","NikoliÄ","NiloviÄ","NjegoÅ¡","OrlandiÄ","OtaÅ¡eviÄ","PaltaÅ¡iÄ","PapiÄ","PaviÄeviÄ","PavliÄeviÄ","PejanoviÄ","PeroviÄ","PerunoviÄ","PetanoviÄ","PetkoviÄ","PetriÄeviÄ","PetroviÄ","Plamenac","Polumenta","PopoviÄ","RadiÄeviÄ","Radlovic","RadojiÄiÄ","RadonÄiÄ","RadonjiÄ","RadovanoviÄ","RadoviÄ","RaduloviÄ","RaiÄeviÄ","RajÄiÄ","RajoviÄ","RamusoviÄ","RaoniÄ","Rastoder","RoloviÄ","SaiÄiÄ","SamardÅ¾iÄ","SaviÄ","SaviÄeviÄ","Scekic","SekuliÄ","SimoviÄ","SkenderoviÄ","SoÅ¡iÄ","StaniÄ","StankoviÄ","StefanoviÄ","StevoviÄ","StijoviÄ","StojanoviÄ","Strugar","SundeÄiÄ","ToÅ¡koviÄ","TodoroviÄ","TomaÅ¡eviÄ","UskokoviÄ","VeÅ¡oviÄ","Visin","VuÄeviÄ","VuÄiÄ","VuÄiniÄ","VuÄuroviÄ","Vuchetich","VujaÄiÄ","VujadinoviÄ","VujanoviÄ","VujoÅ¡eviÄ","VujoviÄ","VukÄeviÄ","VukaÅ¡inoviÄ","VukiÄeviÄ","VukmanoviÄ","VukotiÄ","VukoviÄ","VuksanoviÄ","VuskoviÄ","ZlatiÄanin","ZmajeviÄ","ZogoviÄ","ZverotiÄ"];
	var element = document.createElement("div");
	element.setAttribute("id", "result");

	for(i = 0; i < 10; i++){
		rnd2 = Math.random() * nm3.length | 0;
		if(tp === 1){
			rnd = Math.random() * nm2.length | 0;
			nMs = nm2[rnd] + " " + nm3[rnd2];
			nm2.splice(rnd, 1);
		}else{
			rnd = Math.random() * nm1.length | 0;
			nMs = nm1[rnd] + " " + nm3[rnd2];
			nm1.splice(rnd, 1);
		}
		nm3.splice(rnd2, 1);
		br = document.createElement('br');	
		element.appendChild(document.createTextNode(nMs));
		element.appendChild(br);
	}
	if(document.getElementById("result")){
		document.getElementById("placeholder").removeChild(document.getElementById("result"));
	}		
	document.getElementById("placeholder").appendChild(element);
}