ï»¿/* Argentina */
var nm1 = ["AÃ±a","A","Adro","Agui","Al","Alba","Albar","Alde","Ari","Aris","Arro","Ave","Azu","Ba","Barra","Barran","Bue","CÃ³r","CaÃ±a","Ca","Cale","Cam","Capi","Car","Carca","Cas","Casi","Caste","Cau","Cen","Cente","Cha","Chaca","Chaja","Chara","Chi","Chile","Chim","Chivi","Cin","Cipo","Cole","Como","Conce","Cor","Coro","Cos","Cre","Cres","Cru","Cu","Curu","Cut","Do","Dolo","Em","Emba","Embar","Es","Espe","Esqui","Fa","Fama","Fe","Fede","Fir","Fon","For","GÃ¡","GÃ¡l","Go","Gobe","Gra","Grana","Gua","Guale","Ja","Jar","Joa","Lin","Lu","Ma","Macha","Men","Mendo","Mer","Mo","Mon","Ne","Neco","Neu","Obe","Ola","Olava","PÃ©","Pa","Pal","Palpa","Para","Pe","Per","Perga","Pi","Pira","Plo","Po","Poci","Posa","Qui","Quiti","Ra","Re","Recon","Resi","Ro","Rosa","Ru","Rufi","Sa","Sal","Sala","San An","San Ca","San Car","San Fe","San Fer","San Fra","San Isi","San Ja","San Jo","San Jor","San Ju","San Jua","San Lo","San Lore","San Mar","San Mi","San Ni","San Nico","San Pe","San Ra","San Sal","San Vi","Su","Sun","Suncha","Ta","Tan","Tar","Tarta","Te","Ter","Ti","Tre","Un","Unqui","Ve","Vei","Vein","Vena","ZÃ¡","ZÃ¡ra","Za","Zapa"];
var nm2 = ["bas","buco","bulo","caciÃ³n","cero","cete","chea","ciÃ³n","cia","cinco","cito","co","coy","dÃ³n","da","das","dero","des","dia","dil","do","doba","doro","doza","fino","gai","gal","gano","giales","go","guÃ©","guay","guel","huaia","jÃ¡n","jarÃ­","lares","laye","legos","len","lende","les","leta","lew","li","lipi","lo","lores","los","mante","mas","mat","mes","mino","mosa","nÃ­n","na","nado","nando","nario","neda","nel","no","nos","palÃ¡","pala","pana","po","quÃ©n","quÃ­n","quel","queras","quillo","quina","quista","rÃ¡","rÃ­a","rÃ³n","raÃ±Ã¡","ra","ral","ranÃ¡","ranÃ©","ranza","ras","rata","rate","res","retes","rez","ria","riel","rio","ros","rupÃ¡","ruzÃº","sÃ³n","sadas","sario","spn","ta","tagal","tana","tas","te","telli","tencia","tes","tiago","tier","tiro","to","tuya","va","vedra","vez","vier","ya","yito","yo","yos","zÃº","za"];
/* Bolivia */
var nm3 = ["Aba","Acha","Ai","Aiqui","Ali","Ama","An","Ara","Asce","Ascen","Ato","Ba","Bata","Batal","Be","Beta","Betan","Bo","Bue","CaÃ±a","Ca","Cama","Cami","Capi","Caya","Cha","Chaka","Challa","Chara","Chi","Chim","Cho","Chu","Chulu","Cli","Co","Cobi","Cocha","Col","Colcha","Colo","Colque","Colqui","Colu","Coma","Copa","Cor","Cori","Coroi","Coto","Cul","Culpi","Cura","Epi","Eu","Euca","Gua","Guaya","Hua","Huari","Huata","Huer","Ipa","Ir","Joro","Ju","Juchu","Juku","Ka","Kas","Kata","La","Lahua","Lam","Lampa","Li","Limon","Lla","Llalla","Lu","Luyu","Ma","Macha","Mai","Mapi","Mi","Mine","Miz","Mon","Monte","Mu","O","Oki","Oru","Pa","Padi","Pai","Pata","Pau","Po","Porta","Poto","Pu","Puna","Qui","Re","Ribe","Ro","Robo","Ru","Rurre","Sa","Samai","San Bo","San Bor","San Ca","San Car","San Cri","San Igna","San Ju","San Mi","San Pa","San Pe","Se","Sehue","Sehuen","Si","So","Sora","Tam","Tambi","Tar","Tara","Tari","Ti","Tia","Tiahua","Tira","To","Toto","Tri","Trini","Uru","Uya","Ve","Vela","Vilo","Wa","War","Ya","Yacui","Yu","Yuma"];
var nm4 = ["bamba","baque","bija","billo","buco","cachi","camarca","camaya","cas","cha","chaca","chani","chi","chito","chuc","chuelo","chuy","ciÃ³n","cillas","cito","cuiba","dilla","gua","huanaca","huara","ja","jama","jata","kumari","lÃ³n","lagua","las","liptus","lomi","luyo","luyu","mani","marca","margo","mari","maya","mayu","me","merÃ­n","mi","miri","morÃ©","muri","naco","nata","nawa","neros","nes","ni","nota","nuni","pÃ³","paso","pata","pina","piri","piza","que","quile","quiri","rÃ­n","ragua","ral","ralta","ramerÃ­n","rana","rani","rapa","raque","rata","rete","ri","rija","rillos","rina","rito","ro","roico","ros","ruro","sÃ­","sar","ta","tajata","tero","to","toca","tora","toral","tosÃ­","tus","ya","yu","yuibe","za","zana","zos"];
/* Brazil */
var nm5 = ["Ala","Alagoi","Ame","AnÃ¡","An","Ana","Anani","Ananin","Apa","Apere","AraÃ§a","Ara","Araca","Arai","Arapi","Arara","Ato","Ba","Bar","Barba","Barrei","Bau","Be","Bel","Beto","Blu","Blume","Bo","Botu","Bra","Braga","Ca","Cachoei","Cam","Cama","Canoa","Cara","Carua","Cas","Casca","Casta","Castan","Cau","Cauca","Caxia","Cha","Chape","Co","Colo","Con","Consel","Conta","Cri","Cu","Cuba","Cuia","Curi","Dia","Divi","Dou","Doura","Du","Fei","Flo","Floria","For","Forta","Fra","GoiÃ¢","Gra","Grava","Gua","Guaru","Hor","Horto","Ibi","Il","Impe","Indaia","Ipa","Ita","Itabo","Itape","Itaqua","Ja","Jaboa","Jaca","Jan","Jandi","Jara","Je","Jiu","Jua","Jun","Jundi","Lau","Li","Limei","Lon","Londri","Lu","LuziÃ¢","Ma","Maca","MarÃ­","Mara","Maro","Marom","Mom","Mos","Na","Ni","NilÃ³","Nite","Oli","Osa","Pa","Pai","Pal","Par","Para","Parna","Pelo","Petro","Pin","Pinda","Pira","Po","Pre","Quei","Re","Reci","Rese","Ribei","Ron","Rondo","SÃ£o Be","SÃ£o Ber","SÃ£o Ca","SÃ£o Cae","SÃ£o Car","SÃ£o Jo","SÃ£o Le","SÃ£o Leo","SÃ£o Lu","SÃ£o Pa","SÃ£o Pau","SÃ£o Vi","Sal","Sapu","Se","Ser","Si","So","Sobra","Soro","Su","Suma","Suza","Ta","Tau","Tere","Ti","To","Tole","Ube","Va","Var","Via","Vo","Vol"];
var nm6 = ["Ã§ari","bÃ¡","ba","baia","bara","bo","boraÃ­","bral","buna","cÃ¡ria","cÃ³","caÃ©","ca","caba","caia","caju","cana","capÃ¡","catu","cavel","ceiÃ³","cena","cerica","cetuba","ciÃºma","cicaba","cida","cife","co","cuÃ­ba","da","dares","dema","deua","diaÃ­","dira","dor","dos","drina","gÃ¡","gaba","ganÃ§a","gem","gi","ginha","goinhas","guÃ¡","hais","hal","hangaba","heiro","hoÃ§a","hos","jaÃ­","lÃ©m","ledo","leza","lia","lina","lis","lista","lombo","lotas","mÃ£o","mados","marÃ©","mas","meira","menau","mirim","mon","naÃº","na","nador","naguÃ¡","nau","naus","neiro","nia","ninga","noas","nop","pecÃ³","pevi","pina","pinas","po","poldo","polis","pos","puava","quara","que","quiÃ©","rÃ£o","rÃ³","rÃ³i","raba","raca","rados","raguÃ¡","rato","raz","reiras","rem","ria","rica","ricana","rim","rinha","ru","ruaru","rueri","sÃ­lia","sa","sende","sina","sorÃ³","tÃ£o","tagem","tal","tanhal","tano","tas","tes","tia","tiba","tim","tinga","tininga","tos","triz","tuba","va","vador","vel","xias","zano","zea","zeiro","zia"];
/* Chile */
var nm7 = ["An","Anto","Arau","Ari","Bu","Bui","Bul","CaÃ±e","Ca","Cab","Cabre","Cala","Calbu","Cale","Car","Cara","Carta","Cas","Cau","Cauque","Chai","Chi","Chicu","Chigua","Chim","Chimba","Cho","Chon","Co","Coch","Coi","Col","Colli","Con","Consti","Copia","Coqui","Coquim","Cor","Coro","Cura","Curi","Frei","Fru","Futa","Gra","Grane","Ha","Hacie","Han","Hui","Illa","Iqui","La Ami","La En","La Ense","La Ju","La Jun","La La","La Li","La Pi","La Pin","La Se","La Sere","Lam","Lau","Le","Li","Lima","Lina","Llai","Lo","Lon","Ma","Macha","Me","Meli","Mo","Moli","Mon","Mul","Na","Naci","Nue","Oso","Osor","Ova","Pa","Pai","Pale","Pangui","Par","PeÃ±a","Pe","Pen","Pu","Pun","Purra","Purran","Puye","Puyu","Quil","Ran","Ranca","Rau","Re","Ren","Sala","Ta","Tal","Tala","Talca","Talta","Te","Temu","To","Tooc","Tor","Trai","Va","Val","Valdi","Valle","Valpa","Vi","Vic","Vicu","Vil","Vue","Yu","Yum"];
var nm8 = ["bÃºn","barongo","bel","bo","bu","buco","cÃ³","cÃ³n","ca","cabuco","cagua","chalÃ­","che","chi","ciÃ³n","co","coche","cud","cura","cureo","da","dal","divia","do","dor","flor","ga","gante","gas","gasta","gavÃ­","gena","gol","guÃ©n","gua","haique","huano","huapi","hue","hueco","huin","lÃ¡n","lÃ­","lÃ³n","lahue","lal","lama","lapel","lar","lay","le","lena","lenar","leta","lina","lipe","los","lota","mache","mana","manca","mas","miento","muco","nada","nal","nares","nas","negas","nel","neros","nes","nio","no","pÃ³","pa","pel","piapÃ³","pilla","pulli","quÃ©n","que","quenes","quilo","quique","raÃ­so","rahue","ral","rane","ranque","ras","rena","reo","rero","res","ria","ricÃ³","rica","ro","ronel","rongo","ropa","ros","stad","tÃ©n","ta","tagena","tal","tana","taro","tel","tillar","to","tro","vÃ­","va","via","vier","yante","yehue"];
/* Paraguay */
var nm9 = ["Ãa","Ãacu","Ãacun","Ãu","Aba","Aca","Al","Albo","An","Ante","Ar","Are","Arqui","Arro","Aty","Ayo","Be","Bel","Ben","Bue","Caa","Caapu","Caaza","Camby","Capi","Capia","Car","Cara","Cer","Ciu","Colo","Coro","Des","Desmo","Ede","Embo","En","Encar","Esco","Eu","Euse","FÃ©","Fas","Fassa","Fer","Fi","Fila","Fra","Fue","Fuer","Gua","Guara","Guaya","Guazu","Ho","Hohe","Hor","Horque","Ita","Itana","Itaqu","Itur","Lau","Lea","Lean","Li","Lim","Lo","Ma","Mbo","Mboca","Mbu","Mbuya","Na","Nana","Nara","Naran","Nata","Nem","Obli","Pa","Para","Pi","Piri","Pre","Pri","Re","Repa","San Al","San An","San Be","San Ber","San Ca","San Car","San Co","San Cos","San Isi","San Jo","San Joa","San Jua","San Lo","San Mi","San Pa","San Pe","San Ra","Sapu","Ta","Tacua","Tebi","Toba","Tri","Trini","Vale","Valen","Yabe","Yagua","Yatai","Yby","Ye","Yga","Ypa","Yu"];
var nm10 = ["bÃ­","baÃ­","barÃ©","bar","batÃ­","bebuy","bi","by","byry","caÃ­","carai","chado","ciÃ³n","cia","ciel","cinco","cuÃ¡","cuÃ­","cuaras","cuary","cuatÃ­","cunday","cupÃ©","curubÃ­","dad","day","dencia","dente","do","dro","foa","gado","go","guÃ¡","guarÃ­","guatay","guazÃº","guyry","hay","ja","jal","lÃ©n","la","lar","las","lena","les","licio","ligado","lio","lira","lomas","mÃ­","mÃ­n","ma","mas","men","mena","mero","na","nara","nawa","nel","nia","pÃ¡","pÃ©","pÃºa","peguÃ¡","pio","pucÃº","pus","quera","queta","quyÃ³","ra","rai","ranjal","rapo","ras","rayÃº","reles","retÃ¡","rica","ro","rubÃ­","sardi","scada","tÃ¡","tÃ¡n","tÃ­","tay","tecto","tiago","tora","tos","tuy","ty","wa","yÃ³","yaÃ³","yapey","yaty","yaybi","yos","zapÃ¡"];
/* Peru */
var nm11 = ["Aba","Aban","Aco","Acol","Agua","Am","Anda","Are","As","Asco","Aya","AzÃ¡","AzÃ¡n","Ba","Bam","Bamba","Bar","Barra","Bue","Ca","Caja","Cal","Cam","Cama","Campo","CarÃ¡","Car","Carhua","Cata","Ce","Cele","Celen","Ch","Cha","Chacha","Chan","Chau","Chaupi","Chazu","Chi","Chil","Chin","Cho","Choco","Chon","Chongo","Chosi","Chu","Chulu","Chupa","Co","Coca","Coi","Con","Conta","Cora","Cus","Fe","Ferre","Gua","Guada","Ha","Hacie","HuÃ¡","HuÃ¡nu","Hua","Hual","Huama","Huan","Huanca","Huar","Huara","Hui","Huicu","Ila","Iqui","Jau","Je","Jepe","Ju","Jua","La","La Bre","La Brei","La Hu","La Hua","La O","La Oro","La Pe","La Ri","La Rin","La U","Lagu","Lam","Lamba","Lare","Li","MÃ¡","MÃ¡n","MÃ³","MÃ³r","Ma","Mar","Marca","Maza","Mi","Mo","Mochu","Mol","Molle","Monse","Moque","Moro","Morro","Motu","Moyo","Naz","Nue","Ol","Otu","Oxa","Pa","Paca","Pacan","Pacas","Paco","Pai","Pan","Para","Pati","Pere","Pic","Pico","Pil","Pilco","Pime","Pimen","Pis","Piu","Pu","Puca","Pucal","Pun","Puti","Que","Quere","Qui","Quil","Quilma","Quiru","Re","Rio","Sala","Salave","Sali","Saline","San Cle","San Cleme","San I","San Igna","San Isi","San Je","San Ju","San Jua","San Mi","San Pe","San Ra","San Vi","Sapo","Sati","Se","Sechu","Si","Sica","Sicua","So","Sori","Su","Subta","Sul","Sulla","Sur","TÃº","TÃºcu","Ta","Taba","Tac","Tala","Tam","Tambo","Tar","Ti","Tin","To","Toca","Tora","Tru","Truji","Tum","Uru","Vi","Ya","Yana","Yau","Yun","Yungu","Yuri","Za","Zaru","Zorri"];
var nm12 = ["ba","bamba","bes","bo","bopata","bote","ca","cabamba","cache","cama","canas","cancha","canga","caos","cay","caya","cayo","cha","chacra","che","cho","chuco","chura","cio","co","cocha","colla","comay","cope","cora","cota","cuani","cucho","cume","cungo","dÃ­n","do","garo","goa","goyape","gua","guas","gunas","guyo","huamayo","huaylas","jÃ¡n","ja","jalla","jes","jillo","juÃ­","la","lacio","lana","lao","lara","las","lave","lavera","layo","lendo","liaca","lica","losos","lupe","ma","maguas","manÃ¡","mana","marca","mari","mas","may","mayo","mente","mentel","mey","monga","mos","na","nas","nera","nimo","no","nuco","pÃ©n","pÃ³n","pa","paca","pampa","pata","pe","poyas","que","quio","quipa","rÃ¡s","rÃº","ra","ral","ranca","rata","raz","redo","renÃ©","rial","ritor","ritos","ro","ropÃ³n","rope","ruro","si","sica","ta","tamana","tel","tillo","tina","tipo","tos","tupe","velica","vera","verde","verry","vilca","viri","vista","ya","yape","yas","yeque","za","zuta"];
/* Uruguay */
var nm13 = ["Ace","Ai","Aqua","Arti","At","AtlÃ¡","Ba","Bal","Bar","Be","Bel","Bla","Blan","Ca","Cane","Car","Cardo","Carme","Cas","Casti","Casu","Ce","Cebo","Cer","Chu","Co","Colo","Cur","Del","Die","Diecio","Do","Dolo","Du","Dura","Eci","Ecil","Em","Empa","Flo","Fray","Gui","Isi","Joa","La","Las","Li","Ma","Mal","Maldo","Mari","Mer","Mi","Mon","Nue","Om","Pa","Pal","Pan","Pay","Paysan","Pi","Pie","PiriÃ¡","Por","Porve","Pro","Qie","Ra","Ro","RodrÃ­","Rosa","Rove","Sa","San An","San Ba","San Bau","San Ca","San Car","San Fe","San Ja","San Jo","San Ra","Sara","Sp","Sproa","Ta","Tacua","Tara","To","Tole","Tra","Tran","Trei","Tri","Trini","Tu","Tupa","VelÃ¡","VelÃ¡z","Vi","Vicha"];
var nm14 = ["bÃºes","baÃ©","bracho","cano","cas","cedes","chÃ³n","cha","cho","cio","ciocho","co","da","dal","dero","do","dona","doro","dras","fael","gas","guÃ¡","guas","gues","guez","jas","lÃ©n","lÃ­s","la","latÃ­","ledo","lix","lo","lones","lonia","lores","los","mÃ³n","me","melo","mitas","nas","nes","nia","nicÃ³","nio","nir","no","palme","quÃ­n","queras","quez","quillo","ras","rasco","razno","rembÃ³","rencio","res","reso","resta","riano","rida","rio","ro","sandÃº","sar","sario","scala","supÃ¡","tas","tasar","tes","tiago","tida","tigas","tillos","tina","tista","va","venir","vera","vo"];
var br = "";

function nameGen(){
	var element = document.createElement("div");
	element.setAttribute("id", "result");

	for(i = 0; i < 14; i++){
		if(i < 2){
			rnd = Math.floor(Math.random() * nm1.length);
			rnd2 = Math.floor(Math.random() * nm2.length);
			names = nm1[rnd] + nm2[rnd2];
		}else if(i < 4){
			rnd = Math.floor(Math.random() * nm3.length);
			rnd2 = Math.floor(Math.random() * nm4.length);
			names = nm3[rnd] + nm4[rnd2];
		}else if(i < 6){
			rnd = Math.floor(Math.random() * nm5.length);
			rnd2 = Math.floor(Math.random() * nm6.length);
			names = nm5[rnd] + nm6[rnd2];
		}else if(i < 8){
			rnd = Math.floor(Math.random() * nm7.length);
			rnd2 = Math.floor(Math.random() * nm8.length);
			names = nm7[rnd] + nm8[rnd2];
		}else if(i < 10){
			rnd = Math.floor(Math.random() * nm9.length);
			rnd2 = Math.floor(Math.random() * nm10.length);
			names = nm9[rnd] + nm10[rnd2];
		}else if(i < 12){
			rnd = Math.floor(Math.random() * nm11.length);
			rnd2 = Math.floor(Math.random() * nm12.length);
			names = nm11[rnd] + nm12[rnd2];
		}else{
			rnd = Math.floor(Math.random() * nm13.length);
			rnd2 = Math.floor(Math.random() * nm14.length);
			names = nm13[rnd] + nm14[rnd2];
		}
		br = document.createElement('br');	
		element.appendChild(document.createTextNode(names));
		element.appendChild(br);
	}
	if(document.getElementById("result")){
		document.getElementById("placeholder").removeChild(document.getElementById("result"));
	}		
	document.getElementById("placeholder").appendChild(element);
}