var nm1 = ["Aaron","Abel","Abraham","Abril","Adam","Adan","Adria","Adrian","Agustin","Aimar","Aitor","Alan","Albert","Alberto","Aleix","Alejandro","Alfonso","Alonso","Alvaro","Amir","Ander","Andres","Angel","Antonio","Antonio Jesus","Antonio Jose","Aritz","Arnau","Arturo","Asier","Axel","Biel","Borja","Brais","Bruno","Carles","Carlos","Cesar","Christian","Cristian","Daniel","Dario","David","Denis","Diego","Dylan","Edgar","Eduardo","Elias","Eloy","Emilio","Eneko","Enrique","Enzo","Eric","Erik","Fernando","Ferran","Francisco","Francisco Javier","Francisco Jose","Gabriel","Gael","Gerard","German","Gonzalo","Gorka","Guillem","Guillermo","Hector","Hugo","IÃ±igo","Iago","Ian","Ibai","Ignacio","Iker","Imran","Isaac","Ismael","Israel","Ivan","Izan","Jaime","Jairo","Jan","Jaume","Javier","Jesus","Joan","Joaquin","Joel","Jon","Jonathan","Jordi","Jorge","Jose","Jose Angel","Jose Antonio","Jose Carlos","Jose Luis","Jose Manuel","Jose Maria","Jose Miguel","Josep","Juan","Juan Antonio","Juan Carlos","Juan Francisco","Juan Jose","Juan Manuel","Julen","Julian","Julio","Kevin","Leo","Liam","Luca","Lucas","Luis","Luis Miguel","Luka","Manuel","Marc","Marco","Marcos","Mario","Markel","Marti","Martin","Mateo","Matias","Mauro","Miguel","Miguel Angel","Mikel","Miquel","Mohamed","Moises","Neizan","Nicolas","Nil","Noah","Oier","Oliver","Omar","Oriol","Oscar","Pablo","Pau","Pedro","Pol","Rafael","Ramon","Raul","Rayan","Ricardo","Roberto","Rodrigo","Roger","Ruben","Salvador","Samuel","Santiago","Saul","Sebastian","Sergi","Sergio","Teo","Thiago","Tomas","Unai","Vicente","Victor","Xabier","Xavier","Yago","Yeray","Youssef"];
var nm2 = ["Abril","Adara","Adriana","Africa","Aida","Aina","Ainara","Ainhoa","Ainoa","Aitana","Alba","Alba Maria","Alejandra","Alexia","Alicia","Alma","Almudena","Amaia","Amanda","Amira","Ana","Ana Belen","Ana Isabel","Ana Maria","Andrea","Ane","Angela","Anna","Antia","Ariadna","Arlet","Aroa","Aya","Azahara","Barbara","Beatriz","Belen","Berta","Blanca","Candela","Carla","Carlota","Carmen","Carmen Maria","Carolina","Cayetana","Cecilia","Celia","Chloe","Clara","Claudia","Cloe","Cristina","Daniela","Desiree","Diana","Elena","Elia","Elisa","Elsa","Emma","Erika","Estefania","Estela","Esther","Eva","Eva Maria","Fatima","Gabriela","Gala","Gema","Gemma","Gisela","Gloria","Helena","India","Ines","Ingrid","Inmaculada","Irati","Irene","Iria","Iris","Isabel","Isabel Maria","Isabella","Itziar","Izaro","Jana","Jennifer","Jessica","Jimena","Judit","Judith","Julia","Julieta","June","Laia","Lara","Laura","Leire","Leticia","Leyre","Lia","Lidia","Lina","Lola","Lorena","Lucia","Luna","Lydia","Maialen","Maider","Malak","Manuela","Mar","Mara","Maria","Maria Del Carmen","Maria Del Mar","Maria Isabel","Maria Jose","Mariam","Marina","Mariona","Marta","Martina","Mercedes","Mia","Mireia","Mireya","Miriam","Monica","Nadia","Nahia","Naia","Naiara","Naroa","Natalia","Nayara","Nazaret","Nerea","Neus","Noa","Noelia","Noemi","Nora","Nour","Nuria","Olga","Olivia","Ona","Paloma","Paola","Patricia","Paula","Pilar","Raquel","Rebeca","Rocio","Rosa","Ruth","Salma","Sandra","Sara","Saray","Sheila","Silvia","Sofia","Sonia","Soraya","Susana","Tania","Teresa","Triana","Uxia","Uxue","Valentina","Valeria","Vanesa","Vanessa","Vega","Vera","Veronica","Victoria","Virginia","Yaiza","Yanira","Yasmin","Yasmina","Yolanda","Zaira","Zoe"];
var nm3 = ["Ãlvarez","Ãvila","Abad","Abarquero","Acin","Aisa","Alameda","Albacete","Alcaide","Alcalde","AlfÃ©rez","Alguacil","Alonso","AnglÃ©s","ArÃ¡n","AragÃ³n","AragonÃ©s","Aranda","Ariza","Arriaga","Arroyo","Artigas","Ascaso","AvilÃ©s","Ayerbe","Bacque","BailÃ©n","Balderas","Ballester","Ballesteros","Barbero","BarcelÃ³","Batanero","BaztÃ¡n","BenÃ­tez","BermÃºdez","BescÃ³s","Biel","Bielsa","Biescas","Bilbao","BlÃ¡zquez","BolÃ­var","Bolea","Borobia","Botero","Briones","Burgos","Caballero","Camarero","Canales","Cantero","CapitÃ¡n","Carbonero","Cardenal","Carnicer","Carnicero","Carpenter","Carpentier","Carpintero Charpentier","Carranza","Carreiro","Carretero","CastaÃ±eda","CastejÃ³n","Castellano","Castillero","CastrillÃ³n","CatalÃ¡","CatalÃ¡n","Cedillo","Cerecero","Charpantier","Cherro","Chistau","Colina","Coll","Collado","Conde","Conejero","Contador","Coronel","Corredor","Costa","Criado","CuÃ©llar","Cubero","Cueva","Cuevas","DÃ¡vila","DÃ­az","DÃ­ez","DomÃ­nguez","Duque","DurÃ¡n","EnrÃ­quez","Escribano","EscrivÃ¡","Escudero","EspaÃ±a","Esparraguera","FernÃ¡ndez","FerrÃ³n","Ferrandis","Ferreira","Ferreiro","Ferrer","Ferrero","Ferrufino","Fidalgo","Fonz","Fraile","Fuster o FustÃ©","GÃ¡llego","GÃ¡lvez","GÃ³mez","GÃ³mez Gomis","Gabasa","Gallego","GarcÃ­a","GimÃ©nez","GistaÃ­n","GonzÃ¡lez","Guerrero","GutiÃ©rrez","Halconero","HernÃ¡ndez","Herrera","Herrero","Hidalgo","Hoyo","JimÃ©nez","JuÃ¡rez","Jurado","LÃ©rida","LÃ³pez","Labrador","Lago","Lagos","Laguna","LeÃ±ero","LigÃ¼erre","Linares","Llopis","MÃ¡rquez","MÃ©ndez","MÃ­nguez","Madrid","Malillos","MallÃ©n","Marinero","MarquÃ©s","MartÃ­n","MartÃ­nez","Mayordomo","Melero","MenÃ©ndez","Merino","Mesonero","MiguÃ©lez","Moliner","Molinero","Monedero","Monte","Montemayor","Montes","Montilla","Morata","Moreno","Morterero","MuÃ±oz","NÃ¡poles","NÃºÃ±ez","Navarra","Navarro","Notario","OÃ±ate","Obrero","OcaÃ±a","Olloqui","OrdÃ³Ã±ez","Orellana","Ortiz","Ovejero","PÃ¡ez","PÃ©rez","PadrÃ³n","Pajarero","Panadero","Pastor","PeÃ±a","Pedrero","Pena","Peralta","Peris","Pescador","Piedrabuena","Prado","RabadÃ¡n","Rabellini","Rabellino","Racionero","RamÃ­rez","Ramos","Ravelino","Rey","Riba","Rivera","RodrÃ­guez","Romero","Ruiz","SÃ¡enz","SÃ¡nchez","SabatÃ©","Sabater","SacristÃ¡n","SahagÃºn","Salazar","SaldaÃ±a","Sallent","Sambuesa","Sandoval","SangÃ¼esa","Sanhueza","Santander","Santisteban","Santolaria","Sartori","Sastre","SeÃ±or","Serrano","Sevilla","Siurana","Soldado","Soria","Soriano","SuÃ¡rez","Tarragona","TeixidÃ³","Tejedor","Tejero","Toledano","Toledo","Torrente","Torres","Tudela","VÃ¡zquez","VÃ©lez","Vaca","Val","ValdÃ©s","Valderas","Valdovinos","Valdueza","Valenzuela","Valladares","Valle","Valverde","Vaquero","Vargas","VelÃ¡zquez","Verdugo","Vergara","Villalba","Villalobos","Villarreal","Villegas","YÃ¡Ã±ez","Zamorano","Zanhuesa","Zapatero","Zaragoza","de Herrera","del Valle"];

function nameGen(type){
	var tp = type;
	var br = "";
	var element = document.createElement("div");
	element.setAttribute("id", "result");
	
	for(i = 0; i < 10; i++){
		rnd2 = Math.random() * nm3.length | 0;
		if(tp === 1){
			rnd = Math.random() * nm2.length | 0;
			names = nm2[rnd] + " " + nm3[rnd2];
		}else{
			rnd = Math.random() * nm1.length | 0;
			names = nm1[rnd] + " " + nm3[rnd2];
		}
		br = document.createElement('br');	
		element.appendChild(document.createTextNode(names));
		element.appendChild(br);
	}
	if(document.getElementById("result")){
		document.getElementById("placeholder").removeChild(document.getElementById("result"));
	}		
	document.getElementById("placeholder").appendChild(element);
}