function nameGen(type){
	var nm1 = ["ÃhtÃ¤r","ÃkhmÃ¤t","Ãmir","Ãmircan","Ãmirkhan","ÃxmÃ¤t","ÃxmÃ¤tzÃ¤ki","ÃxmÃ¤tzyan","ÃÄ±Ã±ÄÄ±z","ÃiÃ±Äiz","ÄÃ¤bdelxaliq","ÄÃ¤bdennasir","ÄÃ¤del","ÄÃ¤skÃ¤r","Äabdulla","ÄizzÃ¤tulla","Ä°ldar","Ä°skÃ¤ndÃ¤r","ÅÃ¤hit","ÅÃ¤rif","Åamil","Ahmyetgali","Airat","Albert","Alfrid","Alikber","Alim","Almas","Altynbay","Amazat","Amerhan","Ansar","Arislan","Arslan","Artur","Aydar","Aynur","Ayrat","Azat","Azgar","Biktimer","CihanÅa","Cihansha","Damir","DinmÃ¶xÃ¤mmÃ¤d","Eduard","Elbrus","Emil","Erik","FÃ¤rhÃ¤t","FÃ¤rit","FÃ¤yzulla","Fejzulla","Ferdinand","Ferdinant","Gaziz","IlÅat","Ildar","Ildus","Ilfat","Ilgiz","Ilsat","Ilshat","Ilyas","Irek","IskÃ¤ndÃ¤r","Iskhak","Islametdin","Isxak","KÃ¤rim","Kamil","Kazbek","Khasan","Lenar","Linar","MÃ¤jit","MÃ¶bin","MÃ¶xÃ¤mmÃ¤tÅ¡a","MÃ¶xÃ¤mmÃ¤t","MÃ¶xÃ¤mmÃ¤tcan","MÃ¶xÃ¤mmÃ¤tsafa","Marat","Marsel","Mintimer","NÃ¤cip","Nail","RÃ¤Åit","RÃ¤sÃ¼l","RÃ¶stÃ¤m","Radik","Radiq","Radiy","Radmir","RafaÃ¤l","Rafael","Rafail","Rail","Ramil","Ravil","Rawil","RiÅat","Rinat","Robert","RuÅan","Rudolf","Ruslan","Rustam","Rustem","SÃ¶lÃ¤yman","Sabir","Sabircan","Sabrican","Shamil","Sharifzyan","Tahir","Talgat","Timer","Timerkhan","Timerxan","Timur","ToktamiÅ","Toktamish","XÃ¤bib","XÃ¤bibulla","XÃ¤bir","XÃ¤liulla","XÃ¤mzÃ¤","XÃ¤ydÃ¤r","Xasan","YaÅer","Yasher","Yosyf","ZÃ¤ki","ZÃ¶fÃ¤r","Zagip","Zahit","Zaribzyan","Zinetula"];
	var nm2 = ["ÃlfiÃ¤","ÃliÃ¤","ÃminÃ¤","ÃnisÃ¤","ÃaÃ§ak","Ãulpan","ÄÃ¤liÃ¤","ÄÃ¤yÅÃ¤","ÄÃ¤yÅÃ¤bikÃ¤","Åamsinisa","AdelÃ¤","Adelina","Aibanoo","Aida","Aininoor","AlbinÃ¤","Alfira","Alfiya","AlinÃ¤","AlisÃ¤","Aliya","Alsu","AltynÃ§Ã¼rÃ¤","AltynchÃ¼rÃ¤","AsiÃ¤","Assel","Aybanu","AygÃ¶l","Aygol","Ayninur","Aysilu","Aznagool","Aznagul","BaÄazat","Baghazat","BibiÄÃ¤yÅÃ¤","BikÃ¤","Chachak","Chulpan","Dana","Dilbar","Dinara","Elina","Elmira","ElvirÃ¤","Elza","FÃ¤niya","FÃ¤ridÃ¤","FatÃ­ma","Fatima","FirÃ¼zÃ¤","Firaya","Firdausa","Flyura","GÃ¶lÃ§Ã¤Ã§Ã¤k","GÃ¶lnara","GÃ¶lnaz","GÃ¶lsem","GÃ¶lzada","GÃ¼zÃ¤l","GÃ¼zÃ¤liÃ¤","Galim","Golnara","Gusel","Guzel","Indira","Iririya","Kamilla","LÃ¤lÃ¤","LÃ¤ysÃ¤n","Laysan","Leniza","LiÃ¤","Liana","LiliÃ¤","MÃ¤aryÃ¤m","MÃ¤dinÃ¤","MÃ¤likÃ¤","MÃ¤ryÃ¤m","MÃ¤rziya","Maftukha","Maftuxa","Mavzida","MilÃ¤wÅÃ¤","MilÃ¤wÅa","Nailya","Nurbanu","Nurdjamal","Nurdzhamal","Regina","Renata","Rezeda","RezidÃ¤","Roza","SÃ¶yembikÃ¤","TaÃ±silu","UrazbikÃ¤","VÃ¤rÃ¤ka","VÃ¤silÃ¤","Wenera","XÃ¤birÃ¤","XÃ¤liulla","Xabibcamal","Yana","YuliÃ¤","ZÃ¤ynÃ¤p","ZÃ¶hrÃ¤","ZÃ¶lÃ¤ykha","ZÃ¶lÃ¤yxÃ¤","ZÃ¶lÃ¤yxa","ZahidÃ¤","Zemfira","ZifÃ¤","Zifa","Zilya","Zinara","Zolfiya","Zukhra","Zuxra"];
	var nm3 = ["Ãmirxan","ÄÃ¤limov","Ä°sÃ¤nbÃ¤t","Abdullin","Abrashitov","Adrakhmanov","Akhatov","Akhmadulina","Akhmetov","AliÅ","Arslan","Aslan","Avzalov","Babayev","Baibekov","Bareev","Basharov","Batyrshin","Bekbulatovich","Bilalov","Bilyaletdinov","Bogdanov","Borhan","Bragin","Bronson","Chagaev","Cihanov","Dasayev","Derzhavin","Dinov","Djangirov","Faizulin","Fakhrutdinov","Fattakhov","Fayzulin","Fayzullin","Gabdrakhimov","Gainutdin","Galiev","Galimov","Galiullin","Ganeyev","Garayev","Gareev","Garipov","Gataullin","Gavrilov","Gaziev","Geniatullin","Gildeev","Gimatov","Gimayev","Gizzatulla","Gizzatullin","Grimatov","Gubaidulina","Gusmanov","Hayroudinoff","Ibragimov","Ichmouratov","Islanov","Izmailov","Jalil","KÃ¤rimov","Kabaev","Kalimulin","Kalimullin","Karamzin","Khabibulin","Khafizullin","Khamatov","Kharimov","Khasanov","Khidiatullin","Khismatullin","Khusainov","Khusnullin","Litvinov","Mamashev","Manyurov","Marjani","Markovnikov","Mirzayanov","Mukhametshin","Muratov","Mustafina","Nabiullin","Nabiullina","Nabiyev","Netfullin","Nigmatulin","Nigmatullin","Nureyev","Nurgaliyev","Qursawi","Qutuy","Rachmaninoff","Rahimkulov","Rakhmatullin","Ramazanov","Sadiqov","Safin","Sagdeev","Saideshev","Saitov","Sakaev","Samitov","Shabaev","Shabayev","Shafigulin","Shaimiev","Sharifijanov","Shugurov","Syunaev","TaqtaÅ","Tariko","Tazieff","Tuleyev","Tuqay","Utiashev","Valuev","Waxitov","XÃ¤bibullin","Yakhin","Yakupov","Yanbayev","Yarulin","Yarullin","Yusupov","Zainullin","Zaripov","Zhamaletdinov","Ziatdinov","Zinnurov"];
	var nm4 = ["Ãmirxan","ÄÃ¤limova","Ä°sÃ¤nbÃ¤t","Abdullina","Abrashitova","Adrakhmanova","Akhatova","Akhmadulina","Akhmetova","AliÅ","Arslan","Aslan","Avzalova","Babayeva","Baibekova","Bareeva","Basharova","Batyrshin","Bekbulatovich","Bilalova","Bilyaletdinova","Bogdanova","Borhan","Bragin","Bronson","Chagaeva","Cihanova","Dasayeva","Derzhavin","Dinova","Djangirova","Faizulina","Fakhrutdinova","Fattakhova","Fayzulina","Fayzullina","Gabdrakhimova","Gainutdin","Galieva","Galimova","Galiullina","Ganeyeva","Garayeva","Gareeva","Garipova","Gataullina","Gavrilova","Gazieva","Geniatullina","Gildeeva","Gimatova","Gimayeva","Gizzatulla","Gizzatullina","Grimatova","Gubaidulina","Gusmanova","Hayroudinoff","Ibragimova","Ichmouratova","Islanova","Izmailova","Jalil","KÃ¤rimova","Kabaeva","Kalimulina","Kalimullina","Karamzin","Khabibulina","Khafizullina","Khamatova","Kharimova","Khasanova","Khidiatullina","Khismatullina","Khusainova","Khusnullina","Litvinova","Mamasheva","Manyurova","Marjani","Markovnikova","Mirzayanova","Mukhametshin","Muratova","Mustafina","Nabiullina","Nabiullina","Nabiyeva","Netfullina","Nigmatulina","Nigmatullina","Nureyeva","Nurgaliyeva","Qursawi","Qutuy","Rachmaninoff","Rahimkulova","Rakhmatullina","Ramazanova","Sadiqova","Safin","Sagdeeva","Saidesheva","Saitova","Sakaeva","Samitova","Shabaeva","Shabayeva","Shafigulina","Shaimieva","Sharifijanova","Shugurova","Syunaeva","TaqtaÅ","Tariko","Tazieff","Tuleyeva","Tuqay","Utiasheva","Valueva","Waxitova","XÃ¤bibullina","Yakhin","Yakupova","Yanbayeva","Yarulina","Yarullina","Yusupova","Zainullina","Zaripova","Zhamaletdinova","Ziatdinova","Zinnurova"];
	var tp = type;
	var br = "";
	var element = document.createElement("div");
	element.setAttribute("id", "result");
	
	for(i = 0; i < 10; i++){
		if(tp === 1){
			rnd = Math.random() * nm2.length | 0;
			rnd2 = Math.random() * nm4.length | 0;
			names = nm2[rnd] + " " + nm4[rnd2];
			nm2.splice(rnd, 1)
			nm4.splice(rnd2, 1)
		}else{
			rnd = Math.random() * nm1.length | 0;
			rnd2 = Math.random() * nm3.length | 0;
			names = nm1[rnd] + " " + nm3[rnd2];
			nm1.splice(rnd, 1)
			nm3.splice(rnd2, 1)
		}
		br = document.createElement('br');	
		element.appendChild(document.createTextNode(names));
		element.appendChild(br);
	}
	if(document.getElementById("result")){
		document.getElementById("placeholder").removeChild(document.getElementById("result"));
	}		
	document.getElementById("placeholder").appendChild(element);
}