var nm1 = ["Aaron","Abel","Abraham","Abril","Adam","Adan","Adria","Adrian","Agustin","Aimar","Aitor","Alan","Albert","Alberto","Aleix","Alejandro","Alfonso","Alonso","Alvaro","Amir","Ander","Andres","Angel","Antonio","Antonio Jesus","Antonio Jose","Aritz","Arnau","Arturo","Asier","Axel","Biel","Borja","Brais","Bruno","Carles","Carlos","Cesar","Christian","Cristian","Daniel","Dario","David","Denis","Diego","Dylan","Edgar","Eduardo","Elias","Eloy","Emilio","Eneko","Enrique","Enzo","Eric","Erik","Fernando","Ferran","Francisco","Francisco Javier","Francisco Jose","Gabriel","Gael","Gerard","German","Gonzalo","Gorka","Guillem","Guillermo","Hector","Hugo","Iñigo","Iago","Ian","Ibai","Ignacio","Iker","Imran","Isaac","Ismael","Israel","Ivan","Izan","Jaime","Jairo","Jan","Jaume","Javier","Jesus","Joan","Joaquin","Joel","Jon","Jonathan","Jordi","Jorge","Jose","Jose Angel","Jose Antonio","Jose Carlos","Jose Luis","Jose Manuel","Jose Maria","Jose Miguel","Josep","Juan","Juan Antonio","Juan Carlos","Juan Francisco","Juan Jose","Juan Manuel","Julen","Julian","Julio","Kevin","Leo","Liam","Luca","Lucas","Luis","Luis Miguel","Luka","Manuel","Marc","Marco","Marcos","Mario","Markel","Marti","Martin","Mateo","Matias","Mauro","Miguel","Miguel Angel","Mikel","Miquel","Mohamed","Moises","Neizan","Nicolas","Nil","Noah","Oier","Oliver","Omar","Oriol","Oscar","Pablo","Pau","Pedro","Pol","Rafael","Ramon","Raul","Rayan","Ricardo","Roberto","Rodrigo","Roger","Ruben","Salvador","Samuel","Santiago","Saul","Sebastian","Sergi","Sergio","Teo","Thiago","Tomas","Unai","Vicente","Victor","Xabier","Xavier","Yago","Yeray","Youssef"];

var nm2 = ["Abril","Adara","Adriana","Africa","Aida","Aina","Ainara","Ainhoa","Ainoa","Aitana","Alba","Alba Maria","Alejandra","Alexia","Alicia","Alma","Almudena","Amaia","Amanda","Amira","Ana","Ana Belen","Ana Isabel","Ana Maria","Andrea","Ane","Angela","Anna","Antia","Ariadna","Arlet","Aroa","Aya","Azahara","Barbara","Beatriz","Belen","Berta","Blanca","Candela","Carla","Carlota","Carmen","Carmen Maria","Carolina","Cayetana","Cecilia","Celia","Chloe","Clara","Claudia","Cloe","Cristina","Daniela","Desiree","Diana","Elena","Elia","Elisa","Elsa","Emma","Erika","Estefania","Estela","Esther","Eva","Eva Maria","Fatima","Gabriela","Gala","Gema","Gemma","Gisela","Gloria","Helena","India","Ines","Ingrid","Inmaculada","Irati","Irene","Iria","Iris","Isabel","Isabel Maria","Isabella","Itziar","Izaro","Jana","Jennifer","Jessica","Jimena","Judit","Judith","Julia","Julieta","June","Laia","Lara","Laura","Leire","Leticia","Leyre","Lia","Lidia","Lina","Lola","Lorena","Lucia","Luna","Lydia","Maialen","Maider","Malak","Manuela","Mar","Mara","Maria","Maria Del Carmen","Maria Del Mar","Maria Isabel","Maria Jose","Mariam","Marina","Mariona","Marta","Martina","Mercedes","Mia","Mireia","Mireya","Miriam","Monica","Nadia","Nahia","Naia","Naiara","Naroa","Natalia","Nayara","Nazaret","Nerea","Neus","Noa","Noelia","Noemi","Nora","Nour","Nuria","Olga","Olivia","Ona","Paloma","Paola","Patricia","Paula","Pilar","Raquel","Rebeca","Rocio","Rosa","Ruth","Salma","Sandra","Sara","Saray","Sheila","Silvia","Sofia","Sonia","Soraya","Susana","Tania","Teresa","Triana","Uxia","Uxue","Valentina","Valeria","Vanesa","Vanessa","Vega","Vera","Veronica","Victoria","Virginia","Yaiza","Yanira","Yasmin","Yasmina","Yolanda","Zaira","Zoe"];

var nm3 = ["Álvarez","Ávila","Abad","Abarquero","Acin","Aisa","Alameda","Albacete","Alcaide","Alcalde","Alférez","Alguacil","Alonso","Anglés","Arán","Aragón","Aragonés","Aranda","Ariza","Arriaga","Arroyo","Artigas","Ascaso","Avilés","Ayerbe","Bacque","Bailén","Balderas","Ballester","Ballesteros","Barbero","Barceló","Batanero","Baztán","Benítez","Bermúdez","Bescós","Biel","Bielsa","Biescas","Bilbao","Blázquez","Bolívar","Bolea","Borobia","Botero","Briones","Burgos","Caballero","Camarero","Canales","Cantero","Capitán","Carbonero","Cardenal","Carnicer","Carnicero","Carpenter","Carpentier","Carpintero Charpentier","Carranza","Carreiro","Carretero","Castañeda","Castejón","Castellano","Castillero","Castrillón","Catalá","Catalán","Cedillo","Cerecero","Charpantier","Cherro","Chistau","Colina","Coll","Collado","Conde","Conejero","Contador","Coronel","Corredor","Costa","Criado","Cuéllar","Cubero","Cueva","Cuevas","Dávila","Díaz","Díez","Domínguez","Duque","Durán","Enríquez","Escribano","Escrivá","Escudero","España","Esparraguera","Fernández","Ferrón","Ferrandis","Ferreira","Ferreiro","Ferrer","Ferrero","Ferrufino","Fidalgo","Fonz","Fraile","Fuster o Fusté","Gállego","Gálvez","Gómez","Gómez Gomis","Gabasa","Gallego","García","Giménez","Gistaín","González","Guerrero","Gutiérrez","Halconero","Hernández","Herrera","Herrero","Hidalgo","Hoyo","Jiménez","Juárez","Jurado","Lérida","López","Labrador","Lago","Lagos","Laguna","Leñero","Ligüerre","Linares","Llopis","Márquez","Méndez","Mínguez","Madrid","Malillos","Mallén","Marinero","Marqués","Martín","Martínez","Mayordomo","Melero","Menéndez","Merino","Mesonero","Miguélez","Moliner","Molinero","Monedero","Monte","Montemayor","Montes","Montilla","Morata","Moreno","Morterero","Muñoz","Nápoles","Núñez","Navarra","Navarro","Notario","Oñate","Obrero","Ocaña","Olloqui","Ordóñez","Orellana","Ortiz","Ovejero","Páez","Pérez","Padrón","Pajarero","Panadero","Pastor","Peña","Pedrero","Pena","Peralta","Peris","Pescador","Piedrabuena","Prado","Rabadán","Rabellini","Rabellino","Racionero","Ramírez","Ramos","Ravelino","Rey","Riba","Rivera","Rodríguez","Romero","Ruiz","Sáenz","Sánchez","Sabaté","Sabater","Sacristán","Sahagún","Salazar","Saldaña","Sallent","Sambuesa","Sandoval","Sangüesa","Sanhueza","Santander","Santisteban","Santolaria","Sartori","Sastre","Señor","Serrano","Sevilla","Siurana","Soldado","Soria","Soriano","Suárez","Tarragona","Teixidó","Tejedor","Tejero","Toledano","Toledo","Torrente","Torres","Tudela","Vázquez","Vélez","Vaca","Val","Valdés","Valderas","Valdovinos","Valdueza","Valenzuela","Valladares","Valle","Valverde","Vaquero","Vargas","Velázquez","Verdugo","Vergara","Villalba","Villalobos","Villarreal","Villegas","Yáñez","Zamorano","Zanhuesa","Zapatero","Zaragoza","de Herrera","del Valle"];



function generator$real$spanishNames(type){
	i = Math.floor(Math.random() * 10);


	var tp = type;

	rnd2 = Math.random() * nm3.length | 0;

		if(tp === 1){

			rnd = Math.random() * nm2.length | 0;

			names = nm2[rnd] + " " + nm3[rnd2];

		}else{

			rnd = Math.random() * nm1.length | 0;

			names = nm1[rnd] + " " + nm3[rnd2];

		}

		return names;

}